### ISSUE TITLE
Github action improvements

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#1010]
@jagthedrummer Some suggestions for Github actions that may be useful to downstream apps.

1. Disable the `tag & release` and `version bump` workflows when they are not being run in the starter app repo.  Downstream users can always copy them and enable them for their own purposes but right now they are fairly BT specific.

2. Provide a template for a GH action that will run tests and system tests.  It may be disabled / commented out by default, but it would be helpful for users that don't also use CircleCI.

**Comment by jagthedrummer** [comment]
We added GitHub Actions workflows in https://github.com/bullet-train-co/bullet_train/pull/1106 (and switched to using them for our internal CI purposes).

The `tag & release` and `version bump` workflows are definitely BT specific, but I'm not sure there's a great way to disable them while leaving them in place.

We could potentially add a step to `bin/configure` to remove them completely, but then I think if we made changes to those files in the future it would make for a weird merge when people upgraded their BT version.

I think it may be better to just rely on people removing them from their own copy of the app if they don't want to see the hanging around.

Gonna close this issue.
