### ISSUE TITLE
Should `strong_passwords` default to `false` in development?

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1012]
I find myself tweaking this bit of the Bullet Train initializer a lot to turn off `strong_passwords`.

https://github.com/bullet-train-co/bullet_train/blob/e3b464b4aa7c480265b1636aa94658716192a5bc/config/initializers/bullet_train.rb#L2-L3

Would it be helpful to others to have default to being off in the development environment?

Something like:

```ruby
  config.strong_passwords = !Rails.env.development?
```

**Comment by gazayas** [comment]
Makes sense to me, I remember we added the configuration because some developers preferred that it hadn't been set to `true` by default (before, we had no way of turning the configuration off).

I'll submit a PR just in case.
