### ISSUE TITLE
Troubles with `device_test`

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1082]
It seems that `device_test` has a few undesirable side effects.

Now when a system test fails the output isn't very useful.

To demonstrate, I changed this line:

https://github.com/bullet-train-co/bullet_train/blob/398489ec0e2bddca2a875c11f6639f58121cf61e/test/system/webhooks_system_test.rb#L36

To say:

```ruby
click_on "A Button That Doesn't Exist"
```

And then when I run that test this is the output:

```
Error:
WebhooksSystemTest#test_team_member_registers_for_webhooks_and_then_receives_them_on_a_macbook_pro_15_inch:
Capybara::ElementNotFound: Unable to find link or button "A Button That Doesn't Exist"
    test/system/webhooks_system_test.rb:36:in `block in <class:WebhooksSystemTest>'
    test/application_system_test_case.rb:118:in `instance_eval'
    test/application_system_test_case.rb:118:in `block (2 levels) in device_test'


rails test test/application_system_test_case.rb:116
```

The error message itself is accurate and points to the right place. `Unable to find link or button "A Button That Doesn't Exist"` is the message we'd expect to see, and the first line in the stack trace points directly to `test/system/webhooks_system_test.rb:36` which is good.

But the command that it suggests to re-run the test is incorrect. When I run that, it doesn't run a single test.

```
$ rails test test/application_system_test_case.rb:116
🌱 Generating global seeds.
🌱 Generating test environment seeds.
Run options: --seed 58265

# Running:



Finished in 0.000885s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/jgreen/projects/bullet-train-co/bullet_train/coverage. 13 / 234 LOC (5.56%) covered.
```

The line that it's pointing to is inside the `device_test` helper method itself.

https://github.com/bullet-train-co/bullet_train/blob/398489ec0e2bddca2a875c11f6639f58121cf61e/test/application_system_test_case.rb#L114-L121

So then I tried to run just that one single test by using the file and line number reported in the stack trace, but that also doesn't run a test.

```
$ rails test test/system/webhooks_system_test.rb:36
🌱 Generating global seeds.
🌱 Generating test environment seeds.
Run options: --seed 64382

# Running:



Finished in 0.001553s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/jgreen/projects/bullet-train-co/bullet_train/coverage. 13 / 234 LOC (5.56%) covered.
```

It seems like the `device_test` meta programming is confusing the framework about what counts as a test. Or... something like that.

@kaspth, pinging you just fyi.

**Comment by kaspth** [comment]
Ah! We probably need to ignore those lines in the backtrace cleaner. I'll see if I can come up with something.

**Comment by kaspth** [comment]
@jagthedrummer I'm trying to look into this, but it looks like with the new `SpecReporter` we've lost the rerun snippet that Rails would otherwise generate:

```
3.2.2 ~/code/bullet-train-co/bullet_train-core/tmp/starter main *= r t test/system/account_test.rb -n /user_can_edit_their_account/
🌱 Generating global seeds.
🌱 Generating test environment seeds.
Started with run options -n /user_can_edit_their_account/ --seed 56795

AccountTest
Puma starting in single mode...
* Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: test
*          PID: 15927
* Listening on http://127.0.0.1:3001
Use Ctrl-C to stop
[Screenshot Image]: /Users/kasperhansen/code/bullet-train-co/bullet_train-core/tmp/starter/tmp/screenshots/failures_test_user_can_edit_their_account_on_a_macbook_pro_15_inch.png
  test_user_can_edit_their_account_on_a_macbook_pro_15_inch       FAIL (7.66s)

Failures and errors:
AccountTest
  test_user_can_edit_their_account_on_a_macbook_pro_15_inch       FAIL (7.66s)
        Epic Fail!
        test/system/account_test.rb:18:in `block in <class:AccountTest>'
        test/application_system_test_case.rb:118:in `instance_eval'
        test/application_system_test_case.rb:118:in `block (2 levels) in device_test'

Finished in 7.65971s
1 tests, 1 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/kasperhansen/code/bullet-train-co/bullet_train-core/tmp/starter/coverage. 76 / 199 LOC (38.19%) covered.
```

I'll still try to remove the erroneous `test/application_system_test_case.rb` in the stacktraces.

**Comment by jagthedrummer** [comment]
@kaspth you can still test by choosing a line number within any system test and trying to run just that test.

For instance:

```
rails test test/system/webhooks_system_test.rb:36
```
