### ISSUE TITLE
OpenAPI tests are failing in CI

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1128]
@newstler, can you take a look at the tests failing in CI for the OpenAPI document? I don't really know enough about it to be all that useful.

The failures we're seeing just started either late last week or over the weekend, and so far I haven't been able to pin it down as being related to a particular change.

Also weird is that the test is passing for me (and others) locally but is just failing in CI.

The failing test is `test/controllers/api/open_api_controller_test.rb`. And the errors all look like this:

```
Property `nullable` is not expected here.

33 |   type: string
34 |   description: Primary Time Zone
35 |   nullable: true
36 | locale:
37 |   type: string

Error was generated by the spec rule.
```

There are 70 of those type error reported, and then one of these warnings:

```
Server `url` should not point to example.com or localhost.

 9 |   version: "V1"
10 | servers:
11 |   - url: http://localhost:3001/api/v1
12 | components:
13 |   securitySchemes:

Warning was generated by the no-server-example.com rule.
```

Here's an example of a failure in the `main` branch of the `core` repo:

https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/2116/workflows/acc433d8-0063-4f3a-a30b-15b2ce90ca31/jobs/6738?invite=true#step-119-13418_41

**Comment by jagthedrummer** [comment]
I feel like this test is kind of flaky in general and sometimes fails with errors or warnings for no obvious reason.

For instance here's a run from a couple of weeks ago where it failed on one of my branches: https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/2039/workflows/7816e35e-0104-49a9-be8b-4f6e14f8129c/jobs/6444?invite=true#step-119-7141_76

And then last week that same branch passed without any changes being made to the branch:
https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/2101/workflows/ddfd48c5-0af5-4150-8de2-4c27d465f75b

**Comment by newstler** [comment]
@jagthedrummer Can you try please with `jbuilder-schema` 2.6.1? In 2.6.0 I added `nullable` property based on misreading the specifications, and just now released 2.6.1 which reverts those changes (as well as adding `object` attributes to `items` in arrays).

**Comment by jagthedrummer** [comment]
Thanks @newstler, that did the trick! I think this PR should help to prevent these kinds of mystery problems in the future: https://github.com/bullet-train-co/bullet_train/pull/1129

**Comment by jagthedrummer** [comment]
Looks like I spoke too soon. OpenAPI errors are back this morning, but with a different message.

The new ones are all some variation on this:

```
[28] tmp/openapi.yaml:1223:17 at #/paths/~1teams~1{team_id}~1invitations/post/responses/201/content/application~1json/example/team_id

Example value must conform to the schema: `team_id` property type must be string.

1221 | uuid: '1111'
1222 | from_membership_id: 
1223 | team_id: 
1224 | created_at: 
1225 | updated_at: 

referenced from tmp/openapi.yaml:1216:15 at #/paths/~1teams~1{team_id}~1invitations/post/responses/201/content/application~1json 

Warning was generated by the no-invalid-media-type-examples rule.
```

https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/2125/workflows/9c8dae78-820d-479c-9df6-d54941759dc7/jobs/6772?invite=true#step-119-82296_133

**Comment by jagthedrummer** [comment]
Pinning `jbuilder-schema` to 2.6.1 seemed to fix this: https://github.com/bullet-train-co/bullet_train-core/pull/640
