### ISSUE TITLE
Lock rails JS dependencies to same minor version as rails

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#1140]
https://github.com/bullet-train-co/bullet_train/blob/d955a36c1302a814fac19d22505795b1254136ea/package.json#L12-L16

These dependencies should be locked to something like "~7.0.8" until this repo moves to Rails 7.1. Otherwise the JS dependencies are out of sync with the Rails version and bad things can happen.

**Comment by gazayas** [comment]
Closing this one since we're updated to Rails 7.1.2

https://github.com/bullet-train-co/bullet_train/blob/ebc520f1bb56d990aa263b88be69ff08429283d4/Gemfile#L12

https://github.com/bullet-train-co/bullet_train/blob/ebc520f1bb56d990aa263b88be69ff08429283d4/package.json#L12-L16
