### ISSUE TITLE
GitHub actions should export the RAILS_MASTER_KEY into the environment 

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#1168]
https://github.com/bullet-train-co/bullet_train/blob/0211217230642a8f8f960391bcdbe700e9179c00/.github/workflows/_database_schema_check.yml#L27-L31

If using the rails credentials system, it is necessary to export the RAILS_MASTER_KEY into the environment of runners so that they can decrypt the encrypted credential files.

**Comment by jagthedrummer** [comment]
@olbrich I'm guessing you had to add the master key as a secret in your repo and then you exported that secret value into the env?

Something like this?

```
env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
```

**Comment by olbrich** [comment]
Yes, exactly. I store some secrets using the Rails credentials system and those configs were complaining when running tests and the script that double checks the schema file.

**Comment by jagthedrummer** [comment]
👍 I'll add that as a commented out line that people can enable if they need it.
