### ISSUE TITLE
Different handling for `HIDE_THINGS`

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1174]
Currently we have CI configured to do two entire runs of the test suite, one with `HIDE_THINGS=true` and one with `HIDE_THINGS=false`. And then a bunch of tests either run, or don't depending on that ENV var.

It would be nice if we could do just a single run of the test suite, and have things setup so that `HIDE_THINGS` can be toggled on or off as needed for specific tests.

Part of the challenge is that we currently end up evaluating `HIDE_THINGS` in `config/routes.rb`, which is generally only parsed once, at the beginning of a test run. Maybe instead of trying to have route disappear based on that setting we should continue to allow those paths to be routeable, but have the controller reject them somehow?

**Comment by olbrich** [comment]
@jagthedrummer There is a `reload_routes!` method on `Rails::Application` that may help with this.
