### ISSUE TITLE
Add warning about Heroku costs?

### ISSUE THREAD

**Issue by andyw8** [bullet-train-co/bullet_train#125]
It's my own fault, but I just got a $150 Heroku bill because I tried the Deploy To Heroku button then forgot about it 😭

**Comment by adamlogic** [comment]
I know it only addresses part of this issue, but #126 will at least ensure that there's no Rails Autoscale cost for the default deploy setup.

**Comment by andrewculver** [comment]
@andyw8 Oof. Sorry that happened! We can for sure add a note that clarifies we’re trying to provision production-ready environments that cost real money.

**Comment by andrewculver** [comment]
Added a note about pricing on https://github.com/bullet-train-co/bullet_train . Will add it to the online doc soon as well.

**Comment by andyw8** [comment]
Good news: Heroku kindly refunded the charge once I explained it was a mistake.

**Comment by adamlogic** [comment]
Nobody ever talks about their *positive* experiences with Heroku support, so this makes me very happy. 🥳
