### ISSUE TITLE
crud-field not working after i pulled down the Bullet Train repo on January 8th

### ISSUE THREAD

**Issue by radamnyc** [bullet-train-co/bullet_train#1272]
i am brand new to bullet train and pulled the repo for sha. 2884809d5b2bbaa23d45af4a2c4f59bbdd52886b on January 8th.

the super_scaffolding crud-field options appears to be broken on this release. i have no idea if this was the right way to fix it but I was able to fix it by adding the an ARGV.shift call to bin/super_scaffold in the case statement as shown below.

diff --git a/bin/super-scaffold b/bin/super-scaffold
index 3243b70..693b418 100755
--- a/bin/super-scaffold
+++ b/bin/super-scaffold
@@ -11,6 +11,7 @@ when "crud"
   ARGV.shift
   nil
 when "crud-field"
+  ARGV.shift
   "field"
 when "incoming-webhooks"
   "incoming_webhooks"

**Comment by gazayas** [comment]
@radamnyc What commands did you use to make the new field? I generated a new crud field without any issues with the following:

```
> rails g super_scaffold Project Team name:text_field
> rails g super_scaffold:field Project details:text_field
> rails db:migrate
```

If you have the commands and/or any error messages that would be helpful.

**Comment by jagthedrummer** [comment]
I just started a fresh project and tried the steps that @gazayas suggested and everything worked as expected. @radamnyc, can you provide some more info about exactly what you did when you ran into this problem?

**Comment by gazayas** [comment]
Going to go ahead and close this one out.
