### ISSUE TITLE
Installation steps missing from Getting Started

### ISSUE THREAD

**Issue by freakent** [bullet-train-co/bullet_train#1350]
There is no information on how you actually install Bullet Train for the first time. I assume you clone the git repo but there is nothing to say how or what would be best practice. Someone new to Bullet Train doesn't know how to get started.

**Comment by gazayas** [comment]
Hey @freakent, we should have the README updated with the proper steps soon, give us a bit and we'll ping you again. Thanks for bringing it to our attention!

**Comment by gazayas** [comment]
@freakent Things are back to normal so I'll go ahead and close this issue. Feel free to ask again if anything comes up!
