### ISSUE TITLE
Repo link in README is not replaced

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/bullet_train#1388]
Some why [this code](https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L272) doesn't change the repo in README.

**Comment by jagthedrummer** [comment]
I think this is related to the fact that we had some bad commits on `main`.

**Comment by jagthedrummer** [comment]
I just looked into this and I think it's a legit bug.

There's this line where we ask if you want to setup GitHub:

https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L188

And then on the next line we test it like this:

https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L189

But then further down the script we do some less specific tests, that don't really test what we want to be testing.

https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L269

https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L283

**Comment by jagthedrummer** [comment]
Relatedly, it seems that we only even attempt to replace the repo URL if you **did not** choose to setup GitHub. Which seems less than ideal.

https://github.com/bullet-train-co/bullet_train/blob/c73c9c843f73bb935279b844d59619d9a6b4b560/bin/configure#L269-L273

If you _do_ setup GitHub we ask you for the `ssh` variant of the repo URL and not the `https` variant. But [according to the render docs](https://docs.render.com/deploy-to-render#specifying-a-repository) they need the `https` variant.

> Set the value of repo to the full https:// URL for your Git repo.

I think maybe we should explicitly ask if you want to use Render. If you're planning to deploy to Heroku or literally any other deployment target it doesn't really do you any good to have a "deploy to Render" button on your README. In fact, it could really be counterproductive and send people down a dead end.
