### ISSUE TITLE
super_scaffold occasionally seems to miss out on sort_order

### ISSUE THREAD

**Issue by swombat** [bullet-train-co/bullet_train#1421]
Not entirely sure why, but here are the super_scaffolds I ran, in order that I ran them. The last one is the one lacking sort_order. This is on a repo created from latest version today.

```
rails generate super_scaffold IntelligenceProvider Team name:text_field models:text_area
rails generate super_scaffold:field IntelligenceProvider class_name:text_field
rails generate super_scaffold IntelligenceCredential Team provider_id:super_select{class_name=IntelligenceProvider} api_key:text_field
rails generate super_scaffold ScriptTemplate Team name:text_field public_description:trix_editor structure_guidance:trix_editor --sortable
rails generate super_scaffold TemplateSection ScriptTemplate,Team name:text_field options_count:number_field public_description:trix_editor structure_guidance:trix_editor --sortable
```

`ScriptTemplate` has a correct migration:
```
class CreateScriptTemplates < ActiveRecord::Migration[7.1]
  def change
    create_table :script_templates do |t|
      t.references :team, null: false, foreign_key: true
      t.integer :sort_order
      t.string :name
      t.text :public_description
      t.text :structure_guidance

      t.timestamps
    end
  end
end
```

`TemplateOption` does not:
```
class CreateTemplateSections < ActiveRecord::Migration[7.1]
  def change
    create_table :template_sections do |t|
      t.references :script_template, null: false, foreign_key: true
      t.string :name
      t.integer :options_count
      t.text :public_description
      t.text :structure_guidance

      t.timestamps
    end
  end
end
```

I've temporarily fixed this by adding the field manually.

**Comment by jagthedrummer** [comment]
I just ran the reproduction steps and go the same result.

I tried to simplify the reproduction steps by doing this:

```
rails g super_scaffold Blog Team name:text_field --sortable
rails g super_scaffold Post Blog,Team name:text_field --sortable
```

And both of the migrations ended up with a `sort_order` column. Going to keep poking at it and see if I can figure out what makes it fail.

**Comment by jagthedrummer** [comment]
I can simplify it down to just these two, which fails to get the `sort_order` column on the last model:

```
rails generate super_scaffold ScriptTemplate Team name:text_field public_description:trix_editor structure_guidance:trix_editor --sortable
rails generate super_scaffold TemplateSection ScriptTemplate,Team name:text_field options_count:number_field public_description:trix_editor structure_guidance:trix_editor --sortable
```

**Comment by jagthedrummer** [comment]
Simplifying to this and things work as expected:

```
rails generate super_scaffold ScriptTemplate Team name:text_field --sortable
rails generate super_scaffold TemplateSection ScriptTemplate,Team name:text_field --sortable
```

**Comment by jagthedrummer** [comment]
If I simplify to this (chaning `ScriptTemplate` to just `Template`) then things do work as expected:

```
rails generate super_scaffold Template Team name:text_field --sortable
rails generate super_scaffold TemplateSection Template,Team name:text_field --sortable
```

I don't know if `ScriptTemplate` specifically is causing trouble, or maybe it's something to do with a "two word" parent model? Gonna keep digging.

**Comment by jagthedrummer** [comment]
Seems like maybe it's the "two word parent model" that's triggering the problem. This also fails to add the `sort_order` column to the `TemplateSection` model:

```
rails generate super_scaffold TestTemplate Team name:text_field --sortable
rails generate super_scaffold TemplateSection TestTemplate,Team name:text_field --sortable
```

@gazayas do you have any thoughts on what might cause that to happen?

**Comment by jagthedrummer** [comment]
I think I found the culprit.

https://github.com/bullet-train-co/bullet_train-core/blob/4de1aa9c4711fcfa08f19a758cb4543713bd0163/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L1461

Doing `parent.downcase` here means that we're trying to find `t.references :testtemplate` when we should be trying to find `t.references :test_template`. We should do `parent.underscore` instead.

Seems like maybe we should do the same thing here:

https://github.com/bullet-train-co/bullet_train-core/blob/4de1aa9c4711fcfa08f19a758cb4543713bd0163/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L1354

**Comment by swombat** [comment]
Nicely done!
