### ISSUE TITLE
Gitpod starts with ruby 3.2.2, but bulletrain requires 3.3.0

### ISSUE THREAD

**Issue by PeterMonsson** [bullet-train-co/bullet_train#1427]
Steps to reproduce:
1. Click on gitpod icon on repo homepage
2. Select default gitpod settings
3. See errors in terminal

**Comment by PeterMonsson** [comment]
Updating _ruby_version=ruby-3.3.0 in gitpod.Dockerfile seems to help, but I gitpod gets stuck during validation here:

```
=========================================================================================================================
[2024-04-09 19:31:04] ERROR 19:31:04: Could not load vsce-sign module Cannot find module '@vscode/vsce-sign'
[2024-04-09 19:31:04] ERROR Require stack:
[2024-04-09 19:31:04] ERROR - /ide/out/server-main.js
[2024-04-09 19:31:04] ERROR 19:31:04: Could not load vsce-sign module Cannot find module '@vscode/vsce-sign'
[2024-04-09 19:31:04] ERROR Require stack:
[2024-04-09 19:31:04] ERROR - /ide/out/server-main.js

```

**Comment by jagthedrummer** [comment]
@PeterMonsson you could also try going the other direction and update your copy of BT to use the version of ruby that gitpod is trying to use. That's controlled by the `.ruby-version` file.

https://github.com/bullet-train-co/bullet_train/blob/b5cd751aa83f2fb066ee7fef800e390d2612836c/.ruby-version#L1

If you change that to `3.2.2` and then run `bundle install` that should get everything in agreement.

**Comment by jagthedrummer** [comment]
@PeterMonsson, did you get this working? And if so, is there something that we should do on the BulletTrain side? (Basically I'm trying to figure out if there's anything to do, of if we can close this issue.)
