### ISSUE TITLE
`bin/configure` assumes Debian based system

### ISSUE THREAD

**Issue by coder2000** [bullet-train-co/bullet_train#1435]
I use Arch Linux so my package manager is `pacman` or `yay` if I need to use something from AUR. The configure script as provided by the repo assumes that `dpkg` is available wants to install `postgresql` and `redis` system wide. While that isn't an issue in and of itself I prefer to use docker to run them on a per project basis if needed.

**Comment by coder2000** [comment]
Splitting it up didn't resolve the issue. The issue is that the scripts rely primarily on `dpkg` and `apt-get` which are only available on Debian and derivatives.

**Comment by jagthedrummer** [comment]
@coder2000 Can you please post a stack trace or some details about whatever problem you ran into? The new scripts no longer rely on `dpkg` or `apt-get` for detecting postgres or redis. It should attempt to use `dpkg` for detecting `icu4c` but if your system doesn't have `dpkg` it _should_ just tell you that it knows you don't have `dpkg` and then it should suggest that you ensure that `icu4c` is installed.

https://github.com/bullet-train-co/bullet_train/blob/e2f4afac4ebd780b7332a134567386a2bcccfbd1/bin/configure-scripts/check_icu.rb#L78-L81

What exactly are you seeing?

**Comment by coder2000** [comment]
Ok. Sorry, I missed that part of the script.

**Comment by jagthedrummer** [comment]
@coder2000 if it gives you any problems please report back with some details. We definitely want to make this as smooth as possible.

**Comment by BRGustavoRibeiro** [comment]
Hi! Same problem here on Fedora 40 Sway. 

- **dpkg** is installed through `brew`.
- `libicu` installed on system.
- **icu4c** installed through `brew`.

I honestly have no idea how to fix this.

`You don't have dpkg, so we can't tell if icu4c is installed.`

**Comment by pushcx** [comment]
Here’s the last couple dozen lines of `bin/setup` crashing on Arch:

```
--------------------------------------------------------------------------------
Checking PostgreSQL

You have PostgreSQL installed, but you're using v16.3 and not v14.
Try proceeding without PostgreSQL 14? [Y/n]

Continuing with PostgreSQL v16.3. This might cause problems in the next steps.


--------------------------------------------------------------------------------
Checking Redis


You have redis 7.2.5 installed.


--------------------------------------------------------------------------------
Checking icu4c


/home/pushcx/code/bt/bin/setup-scripts/check_icu.rb:53:in ``': No such file or directory - dpkg (Errno::ENOENT)
        from /home/pushcx/code/bt/bin/setup-scripts/check_icu.rb:53:in `<top (required)>'
        from <internal:/opt/rbenv/versions/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/opt/rbenv/versions/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from bin/setup:33:in `block in <main>'
        from /opt/rbenv/versions/3.3.4/lib/ruby/3.3.0/fileutils.rb:240:in `chdir'
        from /opt/rbenv/versions/3.3.4/lib/ruby/3.3.0/fileutils.rb:240:in `cd'
        from bin/setup:16:in `<main>'
```
