### ISSUE TITLE
Super_scaffold generator: _id field causes error

### ISSUE THREAD

**Issue by swombat** [bullet-train-co/bullet_train#1456]
```
➜  promptcraft git:(main) ✗ rails generate super_scaffold Output PromptExecution,Prompt,Project,Team label:text_field results:text_area input_tokens:number_field output_tokens:number_field message_id:text_field user_rating:number_field
/Users/danieltenner/.rvm/gems/ruby-3.3.0/gems/activesupport-7.1.3.2/lib/active_support/inflector/methods.rb:290:in `const_get': uninitialized constant Message (NameError)
```

This is the message id returned by OpenAI, Anthropic, etc - not an internal id. I _think_ this should be able to work as is, but I guess the workaround will be naming it something else, without `_id` at the end... Feels like it should be possible to have a text field called `something_id` though.

**Comment by ndbroadbent** [comment]
I ran into this as well with fields like `api_token_id` and `token_id` - I'm setting up some models for API integrations where I enter API token IDs and secrets. I asked ChatGPT for some alternatives to `id`:

* api_token_identifier
* api_token_key
* api_token_ref
* api_token_code
* api_token_label
* api_token_uid
* api_token_tag

Maybe I'll go with `identifier` for now. I can see why `_id` is treated as a special case so I don't know if anything needs to change. Maybe the error message could be nicer though.

**Comment by jagthedrummer** [comment]
You can disable this particular `_id` related behavior by including the `{vanilla}` on the field in your super scaffolding command.

For instance:

```
rails generate super_scaffold SomeModel Team some_id:text_field{vanilla}
```

We're supposed to show you a message about that if we can't find the model but there's currently a bug. I think it will be fixed by this PR: https://github.com/bullet-train-co/bullet_train-core/pull/835
