### ISSUE TITLE
Feature Request: Add option to remove Sidekiq + Redis dependency and use GoodJob (Postgres-based Active Job backend)

### ISSUE THREAD

**Issue by ndbroadbent** [bullet-train-co/bullet_train#1490]
Hello, I've enjoyed using Bullet Train so far! I just had a question / feature request: Is it possible to replace the Active Job backend? I'm working on a small internal app where I would like to keep the stack as simple as possible, so it would be great if I could skip Redis and just use Postgres for the database and job queue: https://github.com/bensheldon/good_job
(I think GoodJob is also a decent choice for many medium-sized applications until they hit a certain scale.)
But no problem if this will be too complicated!

**Comment by ndbroadbent** [comment]
Ah I see Redis is also used for Action Cable, so it probably doesn't make sense to deploy a Bullet Train app without Redis. Will close

**Comment by jagthedrummer** [comment]
> Ah I see Redis is also used for Action Cable, so it probably doesn't make sense to deploy a Bullet Train app without Redis.

@ndbroadbent I think this is absolutely correct. But you could still remove Sidekiq and use GoodJob for background processing if you really wanted to. I don't believe that Bullet Train would need to provide any particular accommodations to make that possible.
