### ISSUE TITLE
Deploying to heroku is broken after upgrading to yarn 4

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1496]
Pushing to heroku fails with this error:

```
remote: -----> Installing dependencies        
remote:        Installing node modules (yarn.lock)        
remote:        Unknown Syntax Error: Invalid option name ("--production=false").        
remote:                
remote:        $ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
```

**Comment by jagthedrummer** [comment]
A complicating factor here is that Heroku recommends putting the `heroku/nodejs` buildpack before `heroku/ruby` but that's causing problems because our `build` step in `package.json` assumes that it can use the `bundle` command (for some reason that I don't fully understand at the moment) which isn't installed yet if we follow Heroku's recommendation.

**Comment by deepakmahakale** [comment]
> A complicating factor here is that Heroku recommends putting the `heroku/nodejs` buildpack before `heroku/ruby` but that's causing problems because our `build` step in `package.json` assumes that it can use the `bundle` command (for some reason that I don't fully understand at the moment) which isn't installed yet if we follow Heroku's recommendation.

I can confirm this works as on 25th Jul 2024

**Comment by jagthedrummer** [comment]
Thanks for the confirmation @deepakmahakale. 🤘
