### ISSUE TITLE
Timezone detection is off or not working

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#1504]
I just spun up a new app and then when I went to sign up the timezone detected for me was `(GMT-12:00) International Date Line West` by my actual timezone is `(GMT-06:00) Central Time (US & Canada)`.

**Comment by jhoskins** [comment]
Same. +1

**Comment by jagthedrummer** [comment]
Seems to be related to the recent removal of the global `jquery` alias of `$`.

![CleanShot 2024-06-03 at 12 08 29](https://github.com/bullet-train-co/bullet_train/assets/58702/6e76a96e-7f32-467a-baad-64bab2b6490a)

**Comment by jagthedrummer** [comment]
This is still not working right when you first sign up. Reopening.
