### ISSUE TITLE
[1.7.15] Pagination styles no longer applying.

### ISSUE THREAD

**Issue by zackgilbert** [bullet-train-co/bullet_train#1582]
I upgraded a project from 1.7.14 to 1.7.15 and noticed that the styles are no longer applying to pagination:

What is _should_ look like (1.7.14 version):
<img width="444" alt="Screenshot 2024-07-03 at 4 07 27 PM" src="https://github.com/bullet-train-co/bullet_train/assets/432526/c00fb925-8076-4d0d-9832-1c5da985c6c2">

What 1.7.15 results in:
<img width="216" alt="Screenshot 2024-07-03 at 4 04 04 PM" src="https://github.com/bullet-train-co/bullet_train/assets/432526/f9834875-679b-4f60-929b-5cce1540ecea">

**Comment by jagthedrummer** [comment]
@zackgilbert, I just tested this in 1.7.15 and pagination links are showing up correctly styled for me.

![CleanShot 2024-07-09 at 11 03 50](https://github.com/bullet-train-co/bullet_train/assets/58702/7eda9cb5-ff5a-4c64-ae60-8d124dd8438c)

Can you try inspecting the pagination elements to make sure that `pagy-*` class names are present in the markup?

And can you check the compiled stylesheets linked in your app to see if the CSS rules for them are also present?

I suspect one of the two will be missing, but I'm not sure why.

**Comment by zackgilbert** [comment]
Interesting. Will take a look and see if I can figure out what's going on. Thanks.

**Comment by zackgilbert** [comment]
Very strange... 

At first glance, the styles are NOT matching the classes in the HTML:
<img width="391" alt="Screenshot 2024-07-10 at 12 06 11 PM" src="https://github.com/bullet-train-co/bullet_train/assets/432526/c2a7d12f-c7a3-441d-81c0-734c67732daf">
<img width="236" alt="Screenshot 2024-07-10 at 12 07 07 PM" src="https://github.com/bullet-train-co/bullet_train/assets/432526/6d4280ff-a323-4608-9f68-d575c6a11282">

**Comment by jagthedrummer** [comment]
Ah! The version thing jogged my memory and I remembered this issue: https://github.com/bullet-train-co/bullet_train/issues/1450

**Comment by jagthedrummer** [comment]
(Also, I'm a little surprised that `depfu` hasn't updated `pagy` in the starter repo. Not sure what's up with that.)

**Comment by zackgilbert** [comment]
Whoa. So my apps have an updated pagy version (8.6.3) but yours doesn't, which is why the styles are still working for you?

**Comment by jagthedrummer** [comment]
@zackgilbert yep, that's the thing. The starter repo is currently on `6.5.0` 😬 :

https://github.com/bullet-train-co/bullet_train/blob/9d2e1c3b10aeca961cd844627c95840d7871fa55/Gemfile.lock#L464

There are a decent number of breaking changes listed for `7.0.0` and then `8.0.0` explicitly mentions [changing the class name structure](https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md#changes).

![CleanShot 2024-07-10 at 14 16 11](https://github.com/bullet-train-co/bullet_train/assets/58702/710be1d5-c171-4c87-a3a3-76c0ad05d179)

**Comment by zackgilbert** [comment]
Ah! So I'm not crazy! Yay! Well that explains it. Okay... and for what its worth, I believe avo requires pagy > 7, so not sure how that's resolving correctly. 

Anyways... super good to know... thanks for tracking that down.

**Comment by jagthedrummer** [comment]
> I believe avo requires pagy > 7, so not sure how that's resolving correctly

Hey, that's fun. 🫠

**Comment by swombat** [comment]
avo requires pagy > 7 for the latest version but the current version (which includes a deprecated call to `Rails.application.secrets`...) doesn't.

So, I guess this might be worth updating...
