### ISSUE TITLE
ActionView::Template::Error (The asset "application.light.css" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by JackWetson** [bullet-train-co/bullet_train#16]
First run of bin/dev after bin/configure and bin/setup

`13:42:22 web.1       | ActionView::Template::Error (The asset "application.light.css" is not present in the asset pipeline.`

**Comment by andrewculver** [comment]
@JackWetson I think this is a race condition. The light theme takes a little longer to compile, because it has to run `rake bt:link` first. Can you try refreshing after giving it a little bit to finish compiling and see if it appears?

**Comment by JackWetson** [comment]
> @JackWetson I think this is a race condition. The light theme takes a little longer to compile, because it has to run `rake bt:link` first. Can you try refreshing after giving it a little bit to finish compiling and see if it appears?

@andrewculver can confirm it's race condition indeed!

**Comment by andyw8** [comment]
I also ran into this, refreshing resolved it.

**Comment by andrewculver** [comment]
@gazayas I'm not really sure what we could do to fix this. The web server comes up before the stylesheets are done compiling. 🤷‍♂️ I'll let you noodle on this one a bit.

**Comment by andyw8** [comment]
Perhaps `bundle exec rake bt:link` should be moved to `bin/dev` or `bin/configure`?
