### ISSUE TITLE
"Deploy to Heroku" button doesn't work from created repo

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#1609]
<img width="264" alt="image" src="https://github.com/user-attachments/assets/d1474eef-1c2c-4020-b98e-404b291efdf6">

**Comment by jagthedrummer** [comment]
Maybe we just remove the "Deploy to Heroku" button for a configured repo? Or somehow check to see if the repo is public before asking if they want the button?

**Comment by gazayas** [comment]
> Maybe we just remove the "Deploy to Heroku" button for a configured repo?

I actually like this idea. The original README serves as a primer for getting started with Bullet Train, so it makes sense to me that developers would look at the README and apply any additional configuration (like these deploy buttons) if it's necessary for their use-case, even after the initial setup. We don't necessarily <i>need</i> to have the buttons exist in a new application, as long as we point developers in the right direction.

It may be beneficial to just have solid documentation on how to deploy with each service and link to it in the README too. That would also help to cut down on things to do in `bin/configure` which would make it quicker/smoother for developers to get setup with a new application.

If we <i>do</i> want the buttons though, I submitted #1614 so developers don't have to write in their repository link.

**Comment by jagthedrummer** [comment]
@andrewculver this should be working now. (Assuming you have your Heroku account connected to your GitHub account.)
