### ISSUE TITLE
Gitpod integration not working

### ISSUE THREAD

**Issue by vanam** [bullet-train-co/bullet_train#1672]
Hi,
I came across this project and wanted to give it a try using Gitpod. There are several issues with integration:

1) Wrong ruby version (3.3.1 -> 3.3.4). This has an easy fix in `gitpod.Dockerfile`
```diff
- RUN _ruby_version=ruby-3.3.1 \
+ RUN _ruby_version=ruby-3.3.4 \
```
2) Wrong yarn version (1.22.22 -> 4.2.2). For this I had to manually uninstall yarn and let the setup script install the correct one. This needs to be moved to `gitpod.Dockerfile`

3) Wrong postgres version (12 -> 14). Gitpod uses version 12 in its `gitpod/workspace-postgres` image.
I guess the solution is to use image `workspace-base` and install correct version on your own like in https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-postgresql/Dockerfile

Hope this report helps a bit.

**Comment by jagthedrummer** [comment]
@vanam I just merged this PR that updates the Gitpod setup. Can you give it a shot and let me know if it does the trick for you? https://github.com/bullet-train-co/bullet_train/pull/1708

**Comment by vanam** [comment]
Works like a charm. Thank you
