### ISSUE TITLE
Suggestion: Configure as template repo

### ISSUE THREAD

**Issue by andyw8** [bullet-train-co/bullet_train#17]
This will allow GitHub to display a 'Use This Template' button:

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by andrewculver** [comment]
@andyw8 Yes, 100% going to do this. Need to update `bin/configure`.

**Comment by andrewculver** [comment]
@andyw8 I take it back, I don't think we can do this. When you use that button, it doesn't clone the repository, it rewrites the commit history, which is incompatible with how we allow people to merge in upstream updates from the starter repository. Let me know if you know of a way to make this feature _not_ rewrite the commit history.
