### ISSUE TITLE
Rails  8 Question

### ISSUE THREAD

**Issue by BrettFraley** [bullet-train-co/bullet_train#1774]
Perhaps this is not the place to ask, but what do future plans to migrate and upgrade to Rails 8 look like at this point?

Thanks in advance for any feedback .

**Comment by jagthedrummer** [comment]
Hey @BrettFraley we'll definitely be updating to Rails 8 soonish. We've been giving it a little time in the wild to allow it to get "fully baked" before making the switch. I can't promise an exact timeline but it will likely be before the end of the year, or if not, early next year.

**Comment by BrettFraley** [comment]
@jagthedrummer Thank you! That's great news! It gives me enough time to establish what I'm building now and be able to segway into adopting Bullet Train as needed.
