### ISSUE TITLE
Fails with latest `bcrypt`?

### ISSUE THREAD

**Issue by andyw8** [bullet-train-co/bullet_train#18]
I have dug in deeply, but there seems to be a problem with the latest `bcrypt` release (3.1.17):

```
16:48:12 web.1       | Started POST "/users" for 127.0.0.1 at 2022-04-01 16:48:12 -0400
16:48:12 web.1       | Processing by RegistrationsController#create as HTML
16:48:12 web.1       |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"andy@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
16:48:12 web.1       | Completed 500 Internal Server Error in 12ms (ActiveRecord: 0.0ms | Allocations: 1755)
16:48:12 web.1       |
16:48:12 web.1       |
16:48:12 web.1       |
16:48:12 web.1       | LoadError (incompatible library version - /Users/andyw8/.gem/ruby/3.1.1/gems/bcrypt-3.1.17/lib/bcrypt_ext.bundle):
```

I changed the Gemfile to use `3.1.16` and it worked.

I'm using an Apple M1 machine:

```
try_bullet_train main % ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
```

**Comment by gazayas** [comment]
@andyw8 Sorry for the delayed answer, it looks like a lot of people are having trouble running bcrypt on M1 machines:
[I can't use bcrypt on Apple M1 Chip](https://github.com/bcrypt-ruby/bcrypt-ruby/issues/239)
[Issue with devise and bcrypt on a macbook m1 rails install](https://github.com/bcrypt-ruby/bcrypt-ruby/issues/250)

One of the proposed solutions is running `gem install bcrypt --platform=ruby`.

I'm running on Ubuntu and haven't had any problems, but if I find any more information I'll be sure to post here.

**Comment by jagthedrummer** [comment]
We're now on `3.1.19` and it's been a long time on this issue. I'm going to go ahead and close it. Please reopen it if there's still something we should address here.
