### ISSUE TITLE
Fresh Heroku install does not connect to Redis

### ISSUE THREAD

**Issue by evanliewer** [bullet-train-co/bullet_train#1802]
two initializer files have a "if heroku?" conditional.  Heroku is not respecting this.  By removing the condition and leaving the code, it all works

**Comment by jagthedrummer** [comment]
Hey @evanliewer, can you describe the exact problem you were running into? Was an error being thrown, or was the `if heroku?` conditional evaluating to an incorrect value? I'm running a couple of BT apps in heroku and those bits of the initializers are doing what I expect.

**Comment by evanliewer** [comment]
no crashes. I used the deploy to heroku button. In the heroku console I received constant errors of not being able to connect to the redis server. Since it was a fresh install I hadn’t created any redis needs. Removing the if heroku conditional fixed it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jagthedrummer** [comment]
If you used the deploy to heroku button it _should_ have automatically provisioned redis for you. Did you remove it after deploying? (BT depends on redis for a number of things internally, so you'll definitely want to have a redis instance connected to your app.)

**Comment by evanliewer** [comment]
It deployed the redis great. However, For Reddit to run on her Roku, and for sidekick, there needs to be two lines of code dedicated for Roku. Those are the lines of code in the initializer, but what I learned was, they were not being initialize for her Roku when that conditional if statement was present.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jagthedrummer** [comment]
Ah, OK, I think I'm understanding now. Can you run `heroku config` on your app and see if there's a config for `HEROKU_APP_NAME`? If not, are there any other `HEROKU_` configs present?

**Comment by jagthedrummer** [comment]
I just tried creating a new BT app on Heroku and it seems that they no longer populate any of the `HEROKU_*` environment variables.

```
$ heroku config -a heroku-deploy-test-december
=== heroku-deploy-test-december Config Vars

BASE_URL:                 https://heroku-deploy-test-december.herokuapp.com
CLOUDINARY_URL:           cloudinary://353878...@hl...
DATABASE_URL:             postgres://ub...@cd5gks8n4kb20g.cluster-czrs8...
HIDE_THINGS:              true
HONEYBADGER_API_KEY:      hbp_XgMB...
JEMALLOC_ENABLED:         true
LANG:                     en_US.UTF-8
MEMCACHIER_PASSWORD:      D9C5907...
MEMCACHIER_SERVERS:       mc2.dev.ec2.memcachier.com:...
MEMCACHIER_USERNAME:      DA9453
RACK_ENV:                 production
RAILS_AUTOSCALE_URL:      https://adapter.judoscale.com/api/A4...
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_MAX_THREADS:        5
RAILS_SERVE_STATIC_FILES: enabled
REDIS_URL:                rediss://:pce3b14...@ec2-...
SECRET_KEY_BASE:          45c148f...
WEB_CONCURRENCY:          2
```

We need some other way to determine if we're in Heroku.

**Comment by jagthedrummer** [comment]
OK, those ENV vars are apparently part of a Heroku Labs feature that has to be explicitly enabled.

```
heroku labs:enable runtime-dyno-metadata -a heroku-deploy-test-december

$ heroku config -a heroku-deploy-test-december
=== heroku-deploy-test-december Config Vars

...
HEROKU_APP_DEFAULT_DOMAIN_NAME: heroku-deploy-test-december-aea3910a63eb.herokuapp.com
HEROKU_APP_ID:                  27174ac7-...
HEROKU_APP_NAME:                heroku-deploy-test-december
HEROKU_RELEASE_CREATED_AT:      2024-12-16T17:34:12Z
HEROKU_RELEASE_VERSION:         v16
HEROKU_SLUG_COMMIT:             56613ed119...
HEROKU_SLUG_DESCRIPTION:        Deploy 56613ed1
...
```

It doesn't look like we can enable that Labs feature via `app.json`. So there are a few options, I guess.

1. Is there a way to determine that we're on Heroku without that Labs feature?
2. Add documentation about enabling that Labs feature.
3. Can we provide a rake task or some kind of post-deploy hook to enable it automatically? (I suspect that would require an API key, which is a whole new can of worms.)

**Comment by jagthedrummer** [comment]
Thanks for bringing this to our attention @evanliewer! I have a fix ready in a PR that will be out soon. https://github.com/bullet-train-co/bullet_train-core/pull/985
