### ISSUE TITLE
`bin/setup` breaks on "bundle install"

### ISSUE THREAD

**Issue by iudizm** [bullet-train-co/bullet_train#191]
OS: Fedora Linux 35 (Workstation Edition) x86_64 
Kernel: 5.17.9-200.fc35.x86_64
AMD Ryzen 5

<details open>
<summary>bin/setup output</summary>

<pre>
> bin/setup
== Checking dependencies ==
Overmind not found
We recommend installing overmind to run your application processes
Visit https://github.com/DarthSim/overmind#installation for more information.
== Installing dependencies ==
The following gems are missing
 * bullet_train (1.0.72)
 * bullet_train-super_scaffolding (1.0.28)
 * bullet_train-api (1.0.17)
 * bullet_train-themes-light (1.0.16)
 * extended_email_reply_parser (0.5.1)
 * bullet_train-themes-tailwind_css (1.0.10)
 * charlock_holmes (0.7.7)
Install missing gems with `bundle install`
Fetching gem metadata from https://rubygems.org/.......
Using rake 13.0.6
Using builder 3.2.4
Using erubi 1.10.0
Using crass 1.0.6
Using minitest 5.15.0
Using digest 3.1.0
Using timeout 0.2.0
Using racc 1.6.0
Using strscan 3.0.3
Using concurrent-ruby 1.1.10
Using marcel 1.0.2
Using ast 2.4.2
Using rack 2.2.3
Using nio4r 2.5.8
Using aws-partitions 1.590.0
Using jmespath 1.6.1
Using api-pagination 5.0.0
Using bcrypt 3.1.18
Using bindex 0.8.1
Using debug_inspector 1.1.0
Using aws-eventstream 1.2.0
Using chronic 0.10.2
Using public_suffix 4.0.7
Using http-accept 1.7.0
Using awesome_print 1.9.2
Using netrc 0.11.0
Using bundler 2.3.8
Using aws_cf_signer 0.1.3
Using method_source 1.0.0
Using mini_mime 1.1.2
Using zeitwerk 2.5.4
Using cancancan 3.3.0
Using bullet_train-scope_validator 1.0.2
Using unf_ext 0.0.8.1
Using thor 1.2.1
Using mime-types-data 3.2022.0105
Using phonelib 0.6.58
Fetching charlock_holmes 0.7.7
Using msgpack 1.5.1
Using thread-local 1.1.0
Using commonmarker 0.23.4
Using orm_adapter 0.5.0
Using http_accept_language 2.1.1
Using email_reply_parser 0.5.10
Using websocket-extensions 0.1.5
Using fastimage 2.2.6
Using hiredis 0.6.3
Using pwned 2.0.2
Using possessive 1.0.1
Using ruby2_keywords 0.0.5
Using coderay 1.1.3
Using connection_pool 2.2.5
Using faraday-net_http 2.0.3
Using jwt 2.3.0
Using multi_xml 0.6.0
Using htmlentities 4.3.4
Using stripe 6.2.0
Using redis 4.6.0
Using matrix 0.4.2
Using regexp_parser 2.4.0
Using dry-inflector 0.2.1
Using hashie 5.0.0
Using hashids 1.0.6
Using sexp_processor 4.16.1
Using erubis 2.7.0
Using honeybadger 4.12.1
Using childprocess 4.1.0
Using knapsack_pro 3.2.1
Installing charlock_holmes 0.7.7 with native extensions
Using multi_json 1.15.0
Using io-console 0.5.11
Using rails_autoscale_agent 0.11.0
Using unicode-version 1.2.0
Using parallel 1.22.1
Using pg 1.3.5
Using json 2.6.2
Using rexml 3.2.5
Using rubyzip 2.3.2
Using rainbow 3.1.1
Using foreman 0.87.2
Using unicode-display_width 2.1.0
Using i18n 1.10.0
Using tzinfo 2.0.4
Using ruby-progressbar 1.11.0
Using sentry-ruby-core 5.3.1
Using net-protocol 0.1.3
Using parser 3.1.2.0
Using warden 1.2.9
Using minitest-retry 0.2.2
Using nokogiri 1.13.6 (x86_64-linux)
Using puma 5.6.4
Using rack-mini-profiler 3.0.0
Using dry-core 0.7.1
Using rack-accept 0.4.5
Using rack-cors 1.1.1
Using require_all 3.0.0
Using mail 2.7.1
Using aws-sigv4 1.5.0
Using mime-types 3.4.1
Using binding_of_caller 1.0.0
Using addressable 2.8.0
Using websocket-driver 0.7.5
Using mustermann 1.1.1
Using pry 0.14.1
Using figaro 1.2.0
Using sidekiq 6.4.2
Using omniauth 1.9.1
Using rack-test 1.1.0
Using sprockets 4.0.3
Using unicode-emoji 3.1.0
Using faraday 2.3.0
Using postmark 1.22.0
Using activesupport 7.0.3
Using unf 0.1.4
Using net-imap 0.2.3
Using selenium-webdriver 4.1.0
Using code_analyzer 0.5.5
Using rubocop-ast 1.18.0
Using reline 0.3.1
Using xpath 3.2.0
Using net-pop 0.1.1
Using net-smtp 0.3.1
Using sentry-ruby 5.3.1
Using loofah 2.18.0
Using launchy 2.5.0
Using mustermann-grape 1.0.2
Using dry-logic 1.2.0
Using aws-sdk-core 3.131.1
Using css_parser 1.11.0
Using bootsnap 1.11.1
Using globalid 1.0.0
Using pry-stack_explorer 0.6.1
Using sentry-sidekiq 5.3.1
Using domain_name 0.5.20190701
Using rails-dom-testing 2.0.3
Using simpleidn 0.2.1
Using activemodel 7.0.3
Using indefinite_article 0.2.5
Using pagy 5.10.1
Using webdrivers 5.0.0
Using dry-configurable 0.15.0
Using irb 1.4.1
Using factory_bot 6.2.1
Using jsonapi-serializer 2.2.0
Using rails-html-sanitizer 1.4.2
Using letter_opener 1.8.1
Using oauth2 1.4.9
Using rails_best_practices 1.23.1
Using rubocop 1.29.1
Using http-cookie 1.0.4
Using premailer 1.16.0
Using valid_email 0.1.4
Using aws-sdk-kms 1.57.0
Using activerecord 7.0.3
Using omniauth-oauth2 1.7.2
Using dry-container 0.9.0
Using debug 1.5.0
Using rest-client 2.1.0
Using actionview 7.0.3
Using rubocop-performance 1.13.3
Using omniauth-stripe-connect 2.10.1
Using active_hash 3.1.0 from https://github.com/bullet-train-co/active_hash.git (at master@a6628bc)
Using capybara 3.37.1 from https://github.com/teamcapybara/capybara.git (at master@d08e88d)
Using microscope 1.1.1
Using actionpack 7.0.3
Using aws-sdk-s3 1.114.0
Using cloudinary 1.23.0
Using jbuilder 2.11.5
Using dry-types 1.5.1
Using nice_partials 0.1.6
Using railties 7.0.3
Using activejob 7.0.3
Using actioncable 7.0.3
Using activestorage 7.0.3
Using omniauth-rails_csrf_protection 0.1.2
Using grape 1.6.2
Using sprockets-rails 3.4.2
Using cssbundling-rails 1.1.0
Using standard 1.12.1
Using responders 3.0.1
Using jsbundling-rails 1.0.2
Using factory_bot_rails 6.2.0
Using stimulus-rails 1.0.4
Using turbo-rails 1.1.1
Using web-console 4.2.0
Using actionmailer 7.0.3
Using doorkeeper 5.5.4
Using sentry-rails 5.3.1
Using grape-cancan 0.0.3
Using grape-jsonapi 1.0.0
Using grape-swagger 1.4.2
Using cable_ready 5.0.0.pre9
Using actionmailbox 7.0.3
Using actiontext 7.0.3
Using devise 4.8.1
Using rails 7.0.3
Using premailer-rails 1.11.1
Using postmark-rails 0.22.0
Using devise-pwned_password 0.1.9
Using bullet_train-fields 1.0.15
Using bullet_train-has_uuid 1.0.3
Using bullet_train-super_load_and_authorize_resource 1.0.1
Using bullet_train-themes 1.0.12
Using grape_on_rails_routes 0.3.2
Using bullet_train-incoming_webhooks 1.0.1
Using wine_bouncer 1.0.4 from https://github.com/bullet-train-co/wine_bouncer.git (at master@638eef8)
Using bullet_train-integrations 1.0.0
Using bullet_train-integrations-stripe 1.0.6
Using bullet_train-obfuscates_id 1.0.2
Using bullet_train-sortable 1.0.2
Using bullet_train-scope_questions 1.0.2
Using bullet_train-outgoing_webhooks 1.0.4
Using bullet_train-roles 0.1.7
Using capybara-email 3.0.2
Using magic_test 0.0.9
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/rvm/gems/ruby-3.1.2/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/usr/local/rvm/rubies/ruby-3.1.2/bin/ruby -I
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0 -r
./siteconf20220524-13076-b7m3vi.rb extconf.rb
checking for -licui18n... no

***************************************************************************************
*********** icu required (brew install icu4c or apt-get install libicu-dev)
***********
***************************************************************************************
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-3.1.2/bin/$(RUBY_BASE_NAME)
	--with-icu-dir
	--without-icu-dir
	--with-icu-include
	--without-icu-include=${icu-dir}/include
	--with-icu-lib
	--without-icu-lib=${icu-dir}/lib
	--with-icu-i18n-dir
	--without-icu-i18n-dir
	--with-icu-i18n-include
	--without-icu-i18n-include=${icu-i18n-dir}/include
	--with-icu-i18n-lib
	--without-icu-i18n-lib=${icu-i18n-dir}/lib
	--with-icu-i18n-config
	--without-icu-i18n-config
	--with-pkg-config
	--without-pkg-config
	--with-icu-io-dir
	--without-icu-io-dir
	--with-icu-io-include
	--without-icu-io-include=${icu-io-dir}/include
	--with-icu-io-lib
	--without-icu-io-lib=${icu-io-dir}/lib
	--with-icu-io-config
	--without-icu-io-config
	--with-icu-uc-dir
	--without-icu-uc-dir
	--with-icu-uc-include
	--without-icu-uc-include=${icu-uc-dir}/include
	--with-icu-uc-lib
	--without-icu-uc-lib=${icu-uc-dir}/lib
	--with-icu-uc-config
	--without-icu-uc-config
	--with-icui18n-dir
	--without-icui18n-dir
	--with-icui18n-include
	--without-icui18n-include=${icui18n-dir}/include
	--with-icui18n-lib
	--without-icui18n-lib=${icui18n-dir}/lib
	--with-icui18nlib
	--without-icui18nlib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/usr/local/rvm/gems/ruby-3.1.2/extensions/x86_64-linux/3.1.0/charlock_holmes-0.7.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/usr/local/rvm/gems/ruby-3.1.2/gems/charlock_holmes-0.7.7 for inspection.
Results logged to
/usr/local/rvm/gems/ruby-3.1.2/extensions/x86_64-linux/3.1.0/charlock_holmes-0.7.7/gem_make.out

/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in
`run'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tempfile.rb:317:in `open'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in
`build_extension'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in
`block in build_extensions'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in
`each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in
`build_extensions'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/installer.rb:853:in
`build_extensions'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/source/rubygems.rb:204:in
`install'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/worker.rb:54:in
`loop'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.8/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing charlock_holmes (0.7.7), and Bundler
cannot continue.

In Gemfile:
  bullet_train-api was resolved to 1.0.17, which depends on
    bullet_train was resolved to 1.0.72, which depends on
      extended_email_reply_parser was resolved to 0.5.1, which depends on
        charlock_holmes

== Command ["bundle install"] failed ==
</pre>
</details>

Checking if `icu` is installed:
```bash
Installed Packages
Name         : icu
Version      : 69.1
Release      : 6.fc35
Architecture : x86_64
Size         : 642 k
Source       : icu-69.1-6.fc35.src.rpm
Repository   : @System
From repo    : updates
Summary      : International Components for Unicode
URL          : http://site.icu-project.org/
License      : MIT and UCD and Public Domain
Description  : Tools and utilities for developing with icu.

```
 Is there something I can do in order to try out _bullet train_?

**Comment by malachaifrazier** [comment]
Have you tried running `apt-get install libicu-dev`?

**Comment by iudizm** [comment]
I'm using Fedora, so the actual package I needed was [`libicu-devel`](https://packages.fedoraproject.org/pkgs/icu/libicu-devel/) 😅
Runned `dnf install libicu-devel` and it worked.

**Comment by andrewculver** [comment]
This makes me want like a "bin/dependencies" script or something like that, which would check on each platform whether the required packages are installed, etc.

**Comment by jagthedrummer** [comment]
There's been a good amount of work done on `bin/configure` to try to handle dependencies.

https://github.com/bullet-train-co/bullet_train/blob/main/bin/configure#L91-L143

If there are specific platforms or packages that are lacking let's definitely address those, but maybe in more focused issues. I'm going to close this one for now.

**Comment by olbrich** [comment]
I haven't tried it before, but think you can use [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux).  Combine that with a Brewfile, and you might be able to generalize the installation of non-gem dependencies.

**Comment by gazayas** [comment]
I installed Homebrew on my Ubuntu recently, didn't run into any problems with it.
