### ISSUE TITLE
bin/dev causing `setupterm': The terminfo database could not be found. (Reline::Terminfo::TerminfoError)

### ISSUE THREAD

**Issue by harssh** [bullet-train-co/bullet_train#215]
bin/dev or overmind works fine without rails and sidekiq but give below error once rails or sidekiq is called only with bullet train. Working fine with other apps. App was created on June 1st 2022.

```
➜ env | grep TERM  
TERM=xterm-256color
COLORTERM=truecolor
TERM_PROGRAM=Hyper
TERM_PROGRAM_VERSION=3.2.3
TERMINFO=/usr/share/terminfo
```

```
 resolveDir Documents/projects//app/javascript/controllers
js      | path ./**/*_controller.js
web  | .rvm/gems/ruby-3.1.2/gems/reline-0.3.1/lib/reline/terminfo.rb:108:in `setupterm': The terminfo database could not be found. (Reline::Terminfo::TerminfoError)

```

**Comment by gazayas** [comment]
Hello @harssh, since you closed the issue were you able to solve this one? If so, posting the fix would be a great help!

**Comment by harssh** [comment]
@gazayas  I closed it because I moved away from BT to some other platform. But later on I found the solution too so missed mentioning here. 

`echo 'set -g default-terminal "screen-256color' >> ~/.tmux.conf`

Solved it for me.

**Comment by gazayas** [comment]
@harssh I see, thanks!
