### ISSUE TITLE
Please remove the $ from the shell commands in the Readme

### ISSUE THREAD

**Issue by sebastianbachmann** [bullet-train-co/bullet_train#22]
### Expected behaviour:

When i click on the button to copy the command to clone the template repository, i only want to copy the command `git clone git@github.com:bullet-train-co/bullet_train.git your_new_project_name`

### Current behaviuor:

When i click on the button to copy the command to clone the template repository, the command including the `$` gets copied, which results in a `zsh: command not found: $` error after i paste it to my terminal. In order to execute the command, i have to manually remove the `$`

### Possible solution:

Please remove the `$` from the commands so copy/pasting the commands works smoothly

**Comment by andrewculver** [comment]
@sebastianbachmann Doing this. Thanks for the feedback.
