### ISSUE TITLE
running bin/configure results in error: cannot load colorize

### ISSUE THREAD

**Issue by esmale** [bullet-train-co/bullet_train#222]
Cloned the starter repo from scratch and ran `bin/configure` as the starter documentation instructs.  Wind up with this error:

```
rescueready@RescueReady rescue_ready % bin/configure
<internal:/Users/rescueready/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- colorize (LoadError)
	from <internal:/Users/rescueready/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from bin/configure:3:in `<main>'
```

**Comment by esmale** [comment]
The solution appears to be to run `bundle install` prior to running `bin/configure` if you don't have the colorize gem installed already.

**Comment by esmale** [comment]
Happy to open a PR and update the documentation if that's the desired fix for this problem.

**Comment by morgler** [comment]
I get the same error even after running `bundle install`. When I do a `bundle exec gem list` I even see the colorize gem.
