### ISSUE TITLE
System tests on macOS: “chromedriver” cannot be opened

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train#228]
Ran `rails test:system` and got the following error on macOS

```
“chromedriver” cannot be opened because the developer cannot be verified.
```
<img width="263" alt="CleanShot 2022-06-13 at 16 02 48@2x" src="https://user-images.githubusercontent.com/104179/173435674-34348246-4c3f-4a91-9b2a-40a8b55d594c.png">

**Comment by pascallaliberte** [comment]
I then clicked "Move to Trash" and now I get this when running `rails test:system`.

```
Selenium::WebDriver::Error::WebDriverError: Unable to find chromedriver. Please download the server from
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

**Comment by pascallaliberte** [comment]
Tried:

```
gem uninstall webdrivers
bundle install
```

No change

**Comment by gazayas** [comment]
@pascallaliberte I had the same issue with Linux, I followed [these steps](https://yizeng.me/2014/04/20/install-chromedriver-and-phantomjs-on-linux-mint/) to get the tests working again:
```shell
> wget -N http://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip -P ~/Downloads
> unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
> sudo mv -f ~/Downloads/chromedriver /usr/local/share/
> sudo chmod +x /usr/local/share/chromedriver
```

**Comment by pascallaliberte** [comment]
Also see #235

**Comment by jagthedrummer** [comment]
@gazayas @pascallaliberte Is this still an issue that we should deal with in some way? I haven't run into this particular flavor of error with chromedriver, though I did run into something kinda similar in https://github.com/bullet-train-co/bullet_train/issues/818, which we fixed in https://github.com/bullet-train-co/bullet_train/pull/819.

**Comment by gazayas** [comment]
@gazayas I got the system tests to pass while using a live browser on MacOSX by setting the following two values specifically to `:selenium_chrome`

https://github.com/bullet-train-co/bullet_train/blob/c09d2ddb5a5a3b9554c659296cd44a6fd3ae93cc/test/application_system_test_case.rb#L26-L27

**Comment by jagthedrummer** [comment]
Cool, sounds like this is fixed.
