### ISSUE TITLE
`bin/resolve` is broken?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#238]
You can see in this example I'm trying to use the `--interactive` mode, but it's concatenating the resulting path.

<img width="1254" alt="Screen Shot 2022-06-15 at 4 05 14 PM" src="https://user-images.githubusercontent.com/217218/173956656-07323168-5315-4fe2-bcf0-d39ed77644b5.png">

**Comment by jagthedrummer** [comment]
I think this was fixed in https://github.com/bullet-train-co/bullet_train-base/pull/55. If not there, it was fixed somewhere along the way. I just tested this and it's working in `main` on the starter repo. Going to close this.
