### ISSUE TITLE
Add React

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#26]
This came up in the Discord chat, so I thought I'd open an issue here.

**Comment by andrewculver** [comment]
@gazayas I think internally we don't want to do this one. I think it falls to folks in the community who like React to push that forward.

**Comment by andrewculver** [comment]
Although I'll say this, if someone who was already on our team was really itching to play around with React and wanted to do an integration guide, then I'd encourage them to do it on our dime. But it doesn't interest me personally.

**Comment by gazayas** [comment]
@andrewculver Got it, I'll go ahead and close the PR then.
