### ISSUE TITLE
Debugging lines included in fresh tests

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#283]
I just generated a new project and ran `MAGIC_TEST=1 rails test:system` and there are two spots where it hangs for debugging. One with `binding.pry` and one with `magic_test`.

Is that intentional, or were they accidentally left in?

```
From: /Users/jgreen/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/magic_test-0.0.9/lib/magic_test/support.rb:84 MagicTest::Support#magic_test:

    78: def magic_test
    79:   return unless ENV["MAGIC_TEST"].present?
    80:   empty_cache
    81:   @test_lines_written = 0
    82:   begin
    83:     magic_test_pry_hook
 => 84:     binding.pry
    85:   rescue
    86:     retry
    87:   end
    88: end
```

```
From: /Users/jgreen/projects/bt-test/test/system/basics_test.rb:7 BasicsTest#test_getting_started:

    4: test "getting started" do
    5:   visit root_url
    6:
 => 7:   magic_test
    8: end
```

(I originally accidentally opened this issue on `bullet_train-base`, but I don't think it really belongs there. https://github.com/bullet-train-co/bullet_train-base/issues/73)

**Comment by pascallaliberte** [comment]
Yeah the workaround is to issue an `up` command to place you at the context of your magic_test call.

Hrmm, maybe there's a way to issue that `up` command automatically? I think it's just assumed that you can't.

**Comment by andrewculver** [comment]
This is intentional.
