### ISSUE TITLE
Test failures in new project

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#285]
I generated a new project and did all of the configuration/setup steps and got my application running locally. (Unfortunately I didn't think to run tests at this stage.)

Then I scaffolded a `Project` model and used `super-scaffold` to build a UI. This is working as expected when I run the local server with `bin/dev`.

When I run `rails test` I get several errors that all look generally like this:

```
rails test test/controllers/api/v1/teams_endpoint_test.rb:64
🌱 Generating global seeds.
Run options: --seed 9431

# Running:

caught error of type NoMethodError in after callback inside Grape::Middleware::Formatter : undefined method `scaffolding_absolutely_abstract_creative_concept_ids' for #<Team id: 16, name: "Alternative String Value", slug: nil, created_at: "2022-07-06 17:06:58.369817000 +0000", updated_at: "2022-07-06 17:06:58.801974000 +0000", being_destroyed: nil, time_zone: nil, locale: nil>
F

Failure:
Api::V1::TeamsEndpointTest#test_update [/Users/jgreen/projects/bullet-train-test/test/controllers/api/v1/teams_endpoint_test.rb:72]:
Expected response to be a <2XX: success>, but was a <500: Internal Server Error>
Response body: {"error":"Invalid response"}


rails test test/controllers/api/v1/teams_endpoint_test.rb:64



Finished in 0.606807s, 1.6480 runs/s, 3.2959 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

Just to see if it was something I did I checked my git history and checked out the version of the repo _after_ doing the config/setup steps but _before_ I generated the `Project` model/UI. And the tests still fail in the same way.

The project where this is happening was generated last night (July 5, 2022).

To see if I could reproduce the problem I generated another new project this morning (July 6, 2022) and all of the tests pass.

I then did the same steps for scaffolding a model and UI for `Projects` in my new project and the tests continue to pass.

I'm still very much in the "kick the tires" mode of working with BT so it may be something that I did somewhere along the way.

In the project that's giving me trouble I tried following the steps for "Upgrading Your Bullet Train Application" and it says I'm already up to date. I also tried a `bundle update` to see if a gem was out of date, but that didn't solve the problem either.

Here's the project that's failing the tests: https://github.com/jagthedrummer/bullet-train-test

**Comment by gazayas** [comment]
Hello @jagthedrummer, I made a new Bullet Train app, super scaffolded `Project`, and ran tests with the latest commit. I also cloned your repo at https://github.com/jagthedrummer/bullet-train-test, and in both situations all of the tests are passing for me.

You mentioned the project where this is happening was generated on July 5, 2022. Is there are specific commit I can run the tests against in case there's something I'm missing?

Reading your post it looks like you made all the right steps, but I'll write my steps just in case:
```shell
> git clone git@github.com:bullet-train-co/bullet_train.git test_app
> cd test_app
> bin/configure
> bin/setup
> rails g model Project team:references title:string
> bin/super-scaffold crud Project Team title:text_field
> bundle exec rails test
```

**Comment by jagthedrummer** [comment]
That's really weird. I just tried running the configure and setup steps in that app again and it's still having the same problems with tests.

I also tried dropping and re-creating the database and that didn't help either.

**Comment by jagthedrummer** [comment]
OK, I just figured it out. The problem was that I had a `.env` file that contained `HIDE_THINGS=1` and apparently there are auto-generated tests that assume that we are _not_ hiding things.

Seems like those tests should check `HIDE_THINGS` and not try to test features that are turned off.

(And/or is it useful to even have those tests as part of the application itself, or would they be better in particular gems?)

**Comment by andrewculver** [comment]
@jagthedrummer Thanks for this! You’re right, the test should skip if HIDE_THINGS is enabled. (We leave these tests in the starter repo on purpose, because they let downstream developers confirm they haven’t broken Super Scaffolding templates from working. 👍)

**Comment by gazayas** [comment]
@jagthedrummer I see, this makes more sense now.
I opened #172 a while back because I experienced the same issue, but I haven't touched it in a while.

I ran tests with `HIDE_THINGS` set to true against `main` and yes, they're failing.

**Comment by jagthedrummer** [comment]
Just spent a while banging my head against this again. Would be nice to get the fix merged.

**Comment by jagthedrummer** [comment]
This was fixed by https://github.com/bullet-train-co/bullet_train/pull/172
