### ISSUE TITLE
Theme docs are incorrect

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#313]
I'm looking at the docs here:

https://bullettrain.co/docs/themes

and they reference a bunch of files that are not present in the starter application repo.

What's the proper way to go about changing the default styling?

**Comment by pascallaliberte** [comment]
Hey @jagthedrummer,
For sure the docs should be improved on that point.

Bullet Train is split up in multiple gems/npm packages (where those files come from), and you can overcome this _indirection_ with a tool we built called `bin/resolve`. It tells you the full path of the file, the file of a i18n string and more. There's even a VS Code plugin to make it easy access.

Check out this other page in the docs:
https://bullettrain.co/docs/indirection

**Comment by jagthedrummer** [comment]
Oops, I should have mentioned that I tried to `bin/resolve` several of the files but that it fails with `ArgumentError: unknown keyword: :aliases`.

```
./bin/resolve app/helpers/theme_helper.rb --open
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/digest-3.1.0/lib/digest.rb:20: warning: already initialized constant Digest::REQUIRE_MUTEX
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/jgreen/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
rake aborted!
ArgumentError: unknown keyword: :aliases

Tasks: TOP => bullet_train:resolve
(See full trace by running task with --trace)
```

And passing the `--trace` option doesn't change the output at all.

**Comment by jagthedrummer** [comment]
I just figured out that I _can_ `bin/resolve` if I do `ThemeHelper` instead of using the path listed in the theming docs.

But it's still unclear how to go about

**Comment by jagthedrummer** [comment]
In Discord we traced my `bin/resolve` problems to the fact that I downgraded to Ruby 2.7 (in order to be able to deploy to an AWS Lambda Ruby image). Just mentioning that here in case anyone else runs into the same problem.

**Comment by jagthedrummer** [comment]
The theme docs have been updated multiple times since I opened this issue, and part of the issue was related to me downgrading ruby, so I'm going to close this one.
