### ISSUE TITLE
I18n::MissingInterpolationArgument

### ISSUE THREAD

**Issue by thedumbtechguy** [bullet-train-co/bullet_train#328]
I have a challenge that just surfaced.

I followed everything like I used to, but for some reason this is not working right now.

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/923493/181774073-1b44e472-25a8-4199-81bc-628307a4c9a7.png">

**Comment by thedumbtechguy** [comment]
I figured out more here.

It's because the field that is being used as the "name" is null.

**Comment by jagthedrummer** [comment]
@thedumbtechguy, I'm sorry that this issue sat here for so long without a response. I'm not entirely clear on how reproduce this. Do you think this is something we still need to address?

**Comment by thedumbtechguy** [comment]
I don't think this is valid anymore. Thank you.
