### ISSUE TITLE
System tests failing on fresh install

### ISSUE THREAD

**Issue by activefx** [bullet-train-co/bullet_train#334]
[https://github.com/bullet-train-co/bullet_train/blob/main/test/application_system_test_case.rb](https://github.com/bullet-train-co/bullet_train/blob/main/test/application_system_test_case.rb) is missing helper methods (namely #complete_pricing_page, #complete_payment_page, #start_subscription, and #fill_in_stripe_elements) from the original bullet train repo that are causing some system tests to fail. Adding them back to application_system_test_case.rb solved the issue for me. Believe these tests broke with the addition of the pro billing gems.

**Comment by jagthedrummer** [comment]
This was fixed in https://github.com/bullet-train-co/bullet_train/pull/335
