### ISSUE TITLE
Javascript (Turbo) based navigation breaks OAuth redirects for native apps when the user is not already signed in

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#384]
I'm working on a desktop app that will auth against my BulletTrain app. Everything works well if the user is already signed in to the BT app, but it doesn't work so well if the user is _not_ signed in.

In the desktop app I click the "sign in" button, and that opens a native browser window to my BulletTrain app at:

```
/oauth/authorize?
  client_id=xxx&
  redirect_uri=syncbot://auth-return&
  response_type=code
```

Doorkeeper sees that I'm not signed in and redirects me to `/users/sign_in`.

I enter my credentials and hit the "Sign in" button.

Javascript on the page makes a `POST` request to sign me in. The server accepts the credentials and issues a 302 redirect to the original URL:

```
/oauth/authorize?
  client_id=xxx&
  redirect_uri=syncbot://auth-return&
  response_type=code
```

The Javascript follows that redirect, and makes a `GET` request to the `/oauth/authorize` endpoint.  The authorization on the server side is successful and the server issues a 302 redirect to the `redirect_uri` specified in the original request, which is `syncbot://auth-return`. (`syncbot://` is a custom protocol that is points back to the desktop app.)

At this point the Javascript attempts to follow the redirect, but is blocked by a CORS issue. This error shows up in the developer console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at syncbot://auth-return?code=yyy. (Reason: CORS request not http).

Along with with one:

> TypeError: NetworkError when attempting to fetch resource.

The app just remains on the login page, making it look like nothing happened. If I click the "sign in" button again (or if I just reload the sign in page) I'm redirected into the BT app with the "you are already signed in" messaging.

At this point I can go back to the native app and click the "sign in" button again, and this time everything works as expected because I'm already signed in and there are no Turbo based navigation steps in that part of the OAuth dance.

I'm not sure if we'd need to completely disable Turbo on the sign in page, or if maybe there's a way to only disable it if we can detect that the destination after sign in is an `/oauth` related route.

**Comment by jagthedrummer** [comment]
I ejected the `devise/sessions/new.html.erb` partial and added `data: {turbo: false}` to the form tag and that gets things working better. Now when I sign in to BT I do get redirected back to the desktop app and authentication is successful.

But the browser window just stays on the sign in page since the ultimate redirect location is outside the browser. I probably need to look at having an intermediate page in the redirect chain that displays a message saying "you signed in and we're redirecting you back to the desktop app, you can close this window".

**Comment by jagthedrummer** [comment]
I got something working that only disables Turbo on the login form for oauth based redirects.

In `ApplicationController` I did this:

```ruby
  def user_return_to_is_oauth
    session["user_return_to"].match(/^\/oauth/)
  end
  helper_method :user_return_to_is_oauth
```

And then in `devise/sessions/new.html.erb` I added this to the form tag:

```
data: {turbo: !user_return_to_is_oauth}
```

Would this be something that you'd be interested in pulling into BT proper? If so, would `bullet_train-base` be the appropriate repo for a PR?

**Comment by andrewculver** [comment]
@jagthedrummer That would be amazing! 🙏

**Comment by andrewculver** [comment]
Yes, submit it to `bullet_train-base`. I can’t remember where `devise/sessions/new.html.erb` comes from off the top of my head, but you can PR that repo as well and we’ll handle getting the tests passing.

**Comment by kitebuggy** [comment]
This has been implemented in the sessions controller, which currently fails within the _box layout view in the current version (unable to find method), unless you move this helper block into the application controller.
