### ISSUE TITLE
dash in project name causes issues with module naming

### ISSUE THREAD

**Issue by pfeifferj** [bullet-train-co/bullet_train#40]
having a dash in a project name eg `foo-bar` causes a module `Foo-bar` to be created on line 9 in `config/application.rb`. this doesn't conform to the expected naming convention for modules (eg. Foo_bar) and breaks the `bin/setup` script

**Comment by andrewculver** [comment]
@pfeifferj Sorry for the trouble you ran into and we've got a fix staged for this at https://github.com/bullet-train-co/bullet_train/pull/41 . Will merge as soon as CI passes.
