### ISSUE TITLE
Running `bin/rails g stimulus controllername` overwrites app/javascript/controllers/index.js

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train#402]
When following online examples, there's a command to scaffold a Stimulus controller.

For example, this can be used to create an `appointment_controller.js` file in `app/javascript/controllers`.

```bash
bin/rails g stimulus appointment
```

However, this command also completely overwrites the contents of `app/javascript/controllers/index.js` with this:

```js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppointmentController from "./appointment_controller"
application.register("appointment", AppointmentController)
```

This of course breaks every other Stimulus controllers Bullet Train depends on.

**Comment by pascallaliberte** [comment]
From the [README of stimulus-rails](https://github.com/hotwired/stimulus-rails/blob/main/README.md):

> With an application using a JavaScript bundler, controllers need to be imported and registered directly in the index.js file. But this can be done automatically using either the Stimulus generator (`./bin/rails generate stimulus [controller]`) or the dedicated `stimulus:manifest:update` task. Either will overwrite the `controllers/index.js` file.

This is a legitimate way to use Stimulus and doesn't seem to include a flag to prevent overwriting `app/javascript/controllers/index.js`.

Maybe there's a way to catch that in BT and prevent overwriting `controllers/index.js` automatically? Maybe by overwriting the generator?

**Comment by gazayas** [comment]
@pascallaliberte I opened a PR over at https://github.com/hotwired/stimulus-rails/pull/116, but you can test it out for the time being by using this in the Gemfile and then using the `--append` flag with the same command:

```ruby
gem "stimulus-rails", git: "git@github.com:gazayas/stimulus-rails.git", branch: "append-controllers-to-index"
```

```
bin/rails g stimulus appointment --append
```

**Comment by jagthedrummer** [comment]
This line makes me think that we're doing something we shouldn't:

> // This file is auto-generated by ./bin/rails stimulus:manifest:update

It sounds like we shouldn't manually construct `app/javascript/controllers/index.js` but should allow it to be auto-generated as expected.

I don't yet have a suggestion as to how we should change it. Just noting that it seems like we've strayed off of the happy path for stimulus.
