### ISSUE TITLE
Using `asdf` for managing ruby and node versions

### ISSUE THREAD

**Issue by iseth** [bullet-train-co/bullet_train#409]
Hello i am new to bullet train and was wondering if there has been any discussion on using asdf to manage ruby and nodejs versions?

I noticed the `bin/configure:93` checks to see if node is installed with brew using the `check_package` which function runs the `not_installed?` function.

Any input would be great!

[asdf-vm.com](https://asdf-vm.com/)
[github.com/asdf-vm/asdf](https://github.com/asdf-vm/asdf)

**Comment by jagthedrummer** [comment]
Since Sep of 2022 a number of changes have been made to `bin/configure` and now it's much less dependent on finding things via homebrew. I personally use `asdf` and it's been working fine for me. If there are other problems remaining please do open a new issue.
