### ISSUE TITLE
Color Picker missing translation

### ISSUE THREAD

**Issue by evanliewer** [bullet-train-co/bullet_train#445]
After using a super-scaffold with a color_picker field a i18n error is generated

`translation missing: en.locations.fields.color_picker_value.options`

that translation file has a reference to hexcolor. duplicating that line to color_picker_value will fix the i18n error.  You need to duplicate, because if you rename to hexcolor, it is called by that on the index page

**Comment by andrewculver** [comment]
Yup, this was a bug.
