### ISSUE TITLE
rails not found in bin/configure step

### ISSUE THREAD

**Issue by getaaron** [bullet-train-co/bullet_train#515]
Seems like it's breaking when loading Rails on line 164 

https://github.com/bullet-train-co/bullet_train/blob/b17d4654808682954c50b77a243f6249841628d1/bin/configure#L156-L164

snippet from `bin/configure` output…

```
Running `yarn install`.

  yarn install v1.22.19
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
warning " > @rails/actiontext@7.0.4" has unmet peer dependency "trix@^1.3.1".
warning "@redocly/cli > redoc@2.0.0" has unmet peer dependency "core-js@^3.1.4".
warning "@redocly/cli > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning "@redocly/cli > redoc > style-loader@3.3.1" has unmet peer dependency "webpack@^5.0.0".
  [4/4] Building fresh packages...
  Done in 5.50s.

What is the name of your new application in title case? (e.g. "Some Great Application")
Test App
<internal:/Users/aaron/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rails (LoadError)
	from <internal:/Users/aaron/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from bin/configure:164:in `<main>'
```

the earlier `bundle install` step didn't show any errors

It works the second time after rerunning the script

**Comment by newstler** [comment]
It didn't work for me running the script second time, but worked installing rails and then running script again:

```
gem install rails
bin/configure
```

**Comment by rept** [comment]
Same here, fresh Ruby 3.2 install got the same error in the bin/configure on that same step.  Doing gem install rails first fixed it.

**Comment by jagthedrummer** [comment]
We no longer `require "rails"` in `bin/configure` and I just confirmed that `bin/configure` and `bin/setup` both work with a fresh ruby version with no gems previously installed.
