### ISSUE TITLE
Tests failing with Cuprite.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#527]

**Comment by jagthedrummer** [comment]
```
F

Failure:
AccountTest#test_simulate_restoring_behavior_of_form_fields_on_page_restore_on_macbook_pro_15_inch [/Users/jgreen/projects/seshy-rails/test/system/fields_test.rb:32]:
Expected no js errors, but these errors where found: %s

%o

%o, Error invoking action "$select2:open->fields--super-select#focusOnTextField", , , %s

%o

%o, Error invoking action "$select2:open->fields--super-select#focusOnTextField", 
```

**Comment by gazayas** [comment]
> ```
> F
> 
> Failure:
> AccountTest#test_simulate_restoring_behavior_of_form_fields_on_page_restore_on_macbook_pro_15_inch [/Users/jgreen/projects/seshy-rails/test/system/fields_test.rb:32]:
> Expected no js errors, but these errors where found: %s
> 
> %o
> 
> %o, Error invoking action "$select2:open->fields--super-select#focusOnTextField", , , %s
> 
> %o
> 
> %o, Error invoking action "$select2:open->fields--super-select#focusOnTextField", 
> ```

I'm curious if this is related to https://github.com/bullet-train-co/bullet_train-core/issues/290, will have to run Cuprite tests locally though.

**Comment by jagthedrummer** [comment]
I just tried this again, and the errors I mentioned above are now gone.

I'll try enabling the CircleCI cuprite system tests in a branch/PR to see what happens.

**Comment by jagthedrummer** [comment]
I got the cuprite tests running in CircleCI, but now there's one failure:

```
SuperScaffoldingSystemTest#test_OpenAPI_V3_document_is_still_valid = 6.58 s = E


Error:
SuperScaffoldingSystemTest#test_OpenAPI_V3_document_is_still_valid:
Ferrum::PendingConnectionsError: Request to http://localhost:3001/api/v1/openapi.yaml reached server, but there are still pending connections: http://localhost:3001/api/v1/openapi.yaml
    test/system/super_scaffolding_test.rb:287:in `block in <class:SuperScaffoldingSystemTest>'
```

I think that has to do with use trying to hit `https://localhost:3001` directly, instead of letting capybara figure out where to go (https://github.com/bullet-train-co/bullet_train/blob/main/test/system/super_scaffolding_test.rb#L287C3-L287C3).

I also think that test is redundant and the thing it's testing is better covered by: https://github.com/bullet-train-co/bullet_train/blob/main/test/controllers/api/open_api_controller_test.rb#L4-L19

I opened an issue asking about getting rid of the duplicate test: https://github.com/bullet-train-co/bullet_train/issues/922

**Comment by jagthedrummer** [comment]
I got the standard tests running with Cuprite in https://github.com/bullet-train-co/bullet_train/pull/921, but the tests for Super Scaffolding don't seem to like cuprite. At least not with the default settings. I'm getting `Ferrum::TimeoutError` at seemingly random places. https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/2262/workflows/ddd26ef8-0bd1-402c-ad42-8d47fdf6a586/jobs/10922

**Comment by jagthedrummer** [comment]
I looked into this again today and Cuprite seems to struggle with tests that use `open_new_window`. It seems like it gets confused about which window to be using at any given time. But it seems random. I'm not sure we can support Cuprite in it's current state with our current test suite.

**Comment by jagthedrummer** [comment]
[This PR](https://github.com/bullet-train-co/bullet_train/pull/1771) is my 3rd distinct attempt to get cuprite working. It seems _mostly_ stable locally (but not entirely) and on CI (GitHub actions) there are tons of random failures (deets in that PR).

I don't think it's worth spending more time on this, so I'm going to close this issue. If anybody wants to take a stab at getting it working and can submit a PR with whatever needs to be done I'd be more than happy to take a look and help get it landed.
