### ISSUE TITLE
Confirm authenticator app configuration before really enabling 2FA.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#539]
When someone tries to enable 2FA for their user account, we should ask them to enter a code from the authenticator app and confirm it's valid before actually enabling and enforcing 2FA for their account. This ensures people don't accidentally lock themselves out of their accounts because they enable it but never actually download an authenticator app or configure it properly.

**Comment by bhumi1102** [comment]
https://github.com/bullet-train-co/bullet_train-core/pull/67
