### ISSUE TITLE
`Team#time_zone` should default to UTC and be updated when we know the first user's time zone.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#56]

**Comment by jagthedrummer** [comment]
@andrewculver I'm curious what scenario this is meant to cover. I just did some testing and when you first sign up on step 2 we ask for your team name and your time zone and we apply the time zone selection to both the `User` and the `Team`. When you click the "Add New Team" menu item we also prompt for a time zone for the team there. Is this meant to cover scenarios where you're creating a team by hand in the console or by some other means? If so, would it be reasonable to remove the `allow_nil: true` bit from the `time_zone` validation?

https://github.com/bullet-train-co/bullet_train-core/blob/779fdd93b6414953e3cdfab8c4e4d9e219af47a6/bullet_train/app/models/concerns/teams/base.rb#L25
