### ISSUE TITLE
Gitpod button not working?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#560]
<img width="829" alt="Screen Shot 2022-12-22 at 11 06 04 AM" src="https://user-images.githubusercontent.com/217218/209208462-e368a041-d2f1-454f-b170-5754a43477ee.png">

**Comment by gazayas** [comment]
I was able to get Gitpod running by grabbing the latest version from the repository.

```Dockerfile
# Install Redis.
RUN curl https://packages.redis.io/gpg | sudo apt-key add - \
 && echo "deb https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list \
 && sudo apt-get update \
 && sudo apt-get install -y redis \
 && sudo rm -rf /var/lib/apt/lists/*
```

I'll open a PR here soon
