### ISSUE TITLE
Add way to have local css for overrides

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train#567]
Currently, the main tailwind-powered css file in found inside the current theme's gem. It's parsed by tailwind and included into the `<head>`, all via the theme's own files.

https://github.com/bullet-train-co/bullet_train/blob/17d557a5434d143f9b7cc77536bc9516b8a35a0c/package.json#L37

* There should be a way to have a batteries-included local css file for custom overrides. 
* These overrides should be loaded after all Tailwind generated classes
* The local css file should allow for npm-powered `@import` statements (already permitted via `postcss.config.js` `postcss-import`.
* Ideally, this should allow the use of `@apply` directives that know about classes defined in all the files parsed via Tailwind's `content[]` config.

**Comment by pascallaliberte** [comment]
One easy option that wouldn't work with `@apply` directives is to have a separate yarn script (e.g. `custom:build:css`) that runs `postcss-cli`.

```
$ yarn add --dev postcss-cli
```

in `package.json` scripts:
```json
"custom:build:css": "postcss app/assets/stylesheets/**/*.css -d app/assets/builds/"
```

And then in `head.html`:
```erb
<%= stylesheet_link_tag "application.custom", media: 'all', 'data-turbo-track': 'reload' %>
```

Again, this solution isn't great because using a directive such as `@apply font-sm;`...

```css
.custom-font-sm {
  @apply 'font-sm';
}
```
...would cause the following error:

```bash
CssSyntaxError: /path/to/app/assets/stylesheets/application.custom.css:4:3: The `'font-sm'` class does not exist. If `'font-sm'` is a custom class, make sure it is defined within a `@layer` directive.

  2 | 
  3 | .refine-custom {
> 4 |   @apply 'font-sm';
    |   ^
  5 | }


```

**Comment by pascallaliberte** [comment]
Maybe another approach is to have the theme's own css file somehow reference the app's default `application.css` file.

e.g. `@import ('../../../../app/assets/stylesheets/application.custom.css');`

That would be weird, but is it possible?

**Comment by pascallaliberte** [comment]
Another approach: a custom postcss plugin that uses the `execSync` technique to read the result from `bin/theme` from #521 to start the local custom css file by importing the theme's own `application.css`.

```
/* app/assets/stylesheets/application.custom.css */
@import "%THEME_CSS%"; /* would be picked up by the custom postcss plugin to run `bin/theme` and stick the path in here before running anything else */
```

**Comment by pascallaliberte** [comment]
Some updates on this. We got something much simpler baked into `bin/theme`!

`bin/theme tailwind-stylesheet light` does something neat that will help. It searches the `@candidate_paths` for `light.tailwind.css`. We could set that file locally via a `bin/resolve --eject`, which currently doesn't make it easy.

So I'm going in this direction:

- [ ] Make `bin/resolve` find and eject `light.tailwind.css` OR create a rake task just for setting up a local css (the `@import "light/application";` path will need to be fixed)
- [ ] Add a doc page explaining how to eject this file locally and how to update it

**Comment by pascallaliberte** [comment]
New PRs ready to review. The new technique avoids publishing an npm package by using a path alias that postcss automatically interprets as the full theme gem's stylesheets path.

https://github.com/bullet-train-co/bullet_train/blob/32318df5cf26419c77147695502100ac92de97d3/postcss.config.js#L9-L16

Here's how the path alias is called [from within `light.tailwind.css`](https://github.com/bullet-train-co/bullet_train-core/blob/4ec8a9429b44d22b20084a82af20ee11ae1b3317/bullet_train-themes-light/app/assets/stylesheets/light.tailwind.css#L5):

```
@import "$THEMESTYLESHEETS/light/application.css"; /* alias used to support ejecting the file to local */
```

By default, `bin/resolve` doesn't support resolving the short form `app/assets/stylesheets/light.tailwind.css`. I filed https://github.com/bullet-train-co/bullet_train-core/issues/727 to fix that later.

In the meantime, the new PRs add the following `rake` task, mentioned in the new "Style Sheets" doc page, which ejects the `light.tailwind.css`, taking automatic precedence over the version in the theme gem thanks to the way `bin/theme` searches for a local file override first.

```
> rake bullet_train:themes:light:init_local_css
```

**Comment by pascallaliberte** [comment]
After considering everyone's feedback, and considering the impact of the new postcss-import trick, I'm suggesting now to have a local default stylesheet. In fact, two style sheets:

1. `app/assets/stylesheets/application.css`
2. `app/assets/stylesheets/application.custom.css`

The first loads the current theme's stylesheet dynamically via a postcss alias. And imports the second, meant for customizations. Both will support tailwind `@apply` directives and npm-backed `@import` directives.

This is a departure from the clever no-css tailwind-only theme styling approach, which we could still keep and instead create a new proper `init_local_css` rake task. I'm suggesting we put something where people expect: default style sheets integrated with the theme's styles.

Thoughts?

**Comment by jagthedrummer** [comment]
@pascallaliberte, conceptually I love that idea. I think we can have these stub files _and_ still generally encourage the no-css tailwind-only approach as being The Bullet Train Way. This just acknowledges that there are times when that model breaks down and you need to be able to write a little CSS, and makes it _much_ easier for people to do so. I'll give the PRs a good look next week. Thanks for taking this on!

**Comment by gazayas** [comment]
I'm all about it! Looking forward to checking out the PRs myself.
