### ISSUE TITLE
Add simplecov

### ISSUE THREAD

**Issue by phortx** [bullet-train-co/bullet_train#574]
What do you think about adding simplecov for test coverage reports?

Basically it's just:

- Adding `/coverage` to `.gitignore`
- Adding `simplecov` to `Gemfile`

And adding 2 lines to `test/test_helper.rb` after `require_relative "../config/environment"`:

```ruby
require "simplecov"
SimpleCov.start "rails"
```

**Comment by andrewculver** [comment]
I’m in favor,
