### ISSUE TITLE
Add support for `file_field` based `User` and `Membership` profile photos.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#576]
Historically we've always use Cloudinary for profile photo support and didn't have a fallback. I'd still like to use Cloudinary for profile photos by default if developers have it enabled, but when it's not available, I would like to fall back to allowing them to upload a photo using Active Storage and using that. Let's call this `user_profile_photo` on `Membership` and `profile_photo` on `User`.

**Comment by gazayas** [comment]
I got a head start on this one, will at least try to push a draft pull request this week.
