### ISSUE TITLE
Make drop-down menu wider?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#580]
Just saw this on https://bullettrain.co:

<img width="264" alt="Screen Shot 2022-12-27 at 11 28 38 PM" src="https://user-images.githubusercontent.com/217218/209775267-fcc80d69-5048-4bde-84de-1354de7d7330.png">

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train/pull/615
