### ISSUE TITLE
`super_select` `accepts_new` documentation needs controller logic example.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#601]
The documentation at https://bullettrain.co/docs/field-partials/super-select describes how do configure the field partial, but doesn't provide an example of how to process the payload in the controller.

<img width="534" alt="Screen Shot 2023-01-06 at 9 23 20 AM" src="https://user-images.githubusercontent.com/217218/211065024-43231a0c-a1e9-4dbf-b20a-25be630e9100.png">

We can use [the `join-model` Super Scaffolding example](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train/docs/super-scaffolding.md#6-scaffolding-has-many-through-associations-with-join-model) as a starting point for this documentation. No need to duplicate it into these docs, just reference it as prerequisite knowledge.

The implementation in `process_params` of `app/controllers/account/projects_controller.rb` would look like this:

```
    strong_params[:tag_ids] = create_models_if_new(strong_params[:tag_ids]) do |name|
      @team.projects_tags.find_or_create_by(name: name)
    end
```

We should also an example of creating values on the fly for `super_select` fields that aren't `multiple: true` (e.g. with `create_model_if_new` instead of `create_models_if_new`) For this, we could use [the `belongs_to` Super Select example](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train/docs/super-scaffolding.md#5-scaffolding-belongs_to-associations-team-member-assignments) as a starting point, showing them an example where the user provides an email address and we create a membership and invitation on the fly.

Let's create this as an independent markdown document and link to it under `Advanced Examples` at the bottom of https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train/docs/field-partials/super-select.md .

**Comment by bhumi1102** [comment]
Sounds good! Will tackle this next.

**Comment by jagthedrummer** [comment]
We now have info about how to handle things server side in this section of the docs:

https://bullettrain.co/docs/field-partials/super-select#accepting-new-entries

![CleanShot 2024-11-20 at 12 06 10](https://github.com/user-attachments/assets/e84c05d6-6fb5-433c-b10c-ea110347af14)

**Comment by jagthedrummer** [comment]
Looks like @pascallaliberte added those in https://github.com/bullet-train-co/bullet_train-core/pull/591

I'm going to close this issue.
