### ISSUE TITLE
Bug in `boolean` documentation. 

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#602]
On https://bullettrain.co/docs/field-partials:

<img width="709" alt="Screen Shot 2023-01-06 at 9 39 25 AM" src="https://user-images.githubusercontent.com/217218/211067870-2aa9aa89-3145-4882-8a6e-7f4d6bdf5c0f.png">

Should be one cell to the right.

**Comment by andrewculver** [comment]
Another one:

<img width="787" alt="Screen Shot 2023-01-06 at 9 38 56 AM" src="https://user-images.githubusercontent.com/217218/211067738-5af2e222-86b2-4f29-a609-861333eb708c.png">

Should be one cell to the right.

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-core/pull/60
