### ISSUE TITLE
Breadcrumbs wrong on team settings.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#618]
When I'm on `http://localhost:3000/account/teams/bJYLew/edit` I see the following:

<img width="218" alt="Screen Shot 2023-01-13 at 4 10 21 PM" src="https://user-images.githubusercontent.com/217218/212440006-b03f9e2b-5ff8-4cd3-a16f-a63260913cad.png">

This isn't right. The breadcrumbs should just be "Dashboard > Team Settings".

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-core/pull/69
