### ISSUE TITLE
`Doorkeeper::ApplicationController` intermittently fails on boot

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#638]
Context: https://discord.com/channels/836637622432170028/836637623048601633/1070039125249495120

We override the Doorkeeper layout in the following in `config/application.rb`:

```ruby
config.prepare_to do
  Doorkeeper::ApplicationController.layout "devise"
  ...
end
```

According to [the docs](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views#overriding-layouts), this is the right way to override the layout.

Looking at the error in the Discord chat, it appears that this will call the entire module structure intermittently, so instead of calling `Doorkeeper::ApplicationController`, it calls `UntitledApplication::Application::Doorkeeper::ApplicationController`.

I personally haven't run into this yet, but I thought I'd open an issue in case anyone else runs into it and wants to chime in.

**Comment by jagthedrummer** [comment]
It seems like it will be hard to do anything about this without some reliable reproduction steps.

**Comment by gazayas** [comment]
Agreed. I haven't seen anything about this since either, so I'm okay with closing this one.
