### ISSUE TITLE
`super_select` field does not select items via typing

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#653]
When trying to use super_select via keyboard I noticed that it does not appear to respond to keypresses as a way to select items.  Using arrow keys works fine, but I can't select 'California' by typing 'ca'. This seems to work fine on the [Select2](https://select2.org/getting-started/basic-usage) website.

This is mostly an accessibility concern.

FYI, I haven't yet modified the theme or introduced any javascript.

**Comment by jagthedrummer** [comment]
I just tested this and it seems to have been fixed in https://github.com/bullet-train-co/bullet_train-fields/issues/35 (or possibly somewhere else along the way).
