### ISSUE TITLE
Add support for webp image files

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#658]
This can probably be done by using [modernizr](https://modernizr.com/) to detect the browser feature and add the appropriate css class to the body of the layout, and then configuring esbuild to recognize `webp` as an image format.

**Comment by jagthedrummer** [comment]
@olbrich, can you add a little more detail about what you're wanting to do? Is it that something breaks if you add a webp image in either `public` or `app/assets`?

**Comment by olbrich** [comment]
I think in the default configuration, webp (and afif) images are compiled by the pipeline, but not all browsers support these newer image formats. It's a good practice to use modernizr to detect the capability.  It will add a class to the `html` element like `webp` if it's supported and `no-webp` if not. 

This is primarily useful for writing CSS so you can use webp background images and have them displayed properly with an appropriate fallback.

```css
.webp .banner { url(<%= asset_path("background.webp") %>) }
.no-webp .banner { url(<%= asset_path("background.jpg") %>) }
```

After reading through the [Rail Guides](https://guides.rubyonrails.org/asset_pipeline.html#changing-the-assets-path:~:text=The%20default%20matcher%20for%20compiling%20files%20includes%20application.js%2C%20application.css%20and%20all%20non%2DJS/CSS%20files%20(this%20will%20include%20all%20image%20assets%20automatically)%20from%20app/assets%20folders%20including%20your%20gems%3A), it looks like the asset pipeline will properly pick up these image formats so there may not be any additional configuration required.

**Comment by jagthedrummer** [comment]
I don't think there's anything we need to do here.

I just added `test-image.webp` to my `public/assets` folder, and then referenced it in CSS like this:

```css
#webp-test {
  background-image: url("test-image.webp")
}
```

And it shows up as expected.

Going to close this issue.
