### ISSUE TITLE
DatesHelperTest not setup for multiple devices

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#662]
https://github.com/bullet-train-co/bullet_train/blob/631bee022eb6bdbbbdb2478407a5e382526dfd50/test/system/dates_helper_test.rb#L5

This ends up re-defining a test because the description does not include the device_name.

FWIW, I would probably enable a mobile device in the list of devices tested so there are at least two to avoid this in other tests.

**Comment by jagthedrummer** [comment]
This was fixed somewhere along the way:

https://github.com/bullet-train-co/bullet_train/blob/2ea5c9c136568bae39257af6c8944267b058dc17/test/system/dates_helper_test.rb#L5
