### ISSUE TITLE
Logo support?

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#666]
The initializer at `config/initializers/logo.rb` implies that a logo should be displayed in the top bar of the application, but I'm not seeing that in a freshly generated project. Is there still any logo support, or do I need to eject the layout and modify it? (Built-in support would be ideal. I've already been bitten by upstream CSS changes conflicting with the "old" version of a layout that I had previously ejected.)

**Comment by jagthedrummer** [comment]
It looks like the stuff in `config/initializers/logo.rb` doesn't have much of an effect. But I did find that I can at least get a logo to shop up by setting this config option:

```
BulletTrain::Themes::Light.show_logo_in_account = true
```

I added it to `config/initializers/theme.rb` since there's already a `BulletTrain::Themes::Light` config happening there.

In order to customize the appearance of the logo (and to add the app name next to it) I ended up ejecting `app/views/themes/light/menu/_logo.html.erb`.

I tweaked it to be:

```
<% # Ejected from `bullet_train-themes-light-1.2.11`. %>

<% if BulletTrain::Themes::Light.show_logo_in_account %>
  <div class="flex items-center flex-shrink-0 px-4 bg-primary-900 md:rounded-tl-lg electron-draggable electron-title-bar dark:bg-black dark:bg-opacity-10">
    <%= image_tag image_path("logo/logo.png"), class: 'h-10 w-10 mr-4 rounded-full', origclass: 'theme-logo h-8 w-auto mx-auto' %>
    <h1 class="text-2xl text-white">Seshy</h1>
    <%= render "account/shared/menu/close" %>
  </div>
<% end %>
```

And that got me to this:
![CleanShot 2023-02-24 at 13 02 47](https://user-images.githubusercontent.com/58702/221268889-80569e7a-6832-4bec-9ac5-f9312f0effdf.png)

Just leaving a note in case it'll help anyone down the road.

**Comment by gazayas** [comment]
Thanks for this @jagthedrummer, it looks like some of the configs haven't been documented, we should probably write them in `config/initializers/logo.rb` like you mentioned.

Another one I can think of is this
```ruby
BulletTrain::Themes::Light.navigation = :left
```

Also noticing the dashboard button is rounded at the top-left even though the logo is present.

![Screenshot from 2023-03-23 16-50-11](https://user-images.githubusercontent.com/10546292/227137730-997a9733-fb55-4901-a912-c6b0618d7f67.png)

**Comment by jagthedrummer** [comment]
The two PRs linked above have improved this situation so it's not as confusing and mysterious. I'm going to close this issue.
