### ISSUE TITLE
`rails test:system` fails after clone because assets haven't been compiled.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#694]
Anytime I clone a new copy of the repo, unless I do `bundle install; yarn install; bin/dev` before running the test suite, it fails. Feels wrong that I have to run `bin/dev` before the system test suite runs. Is there a way to check whether assets are present without unnecessarily recompiling them every time we run the test suite?

**Comment by andrewculver** [comment]
Also, kind of feels like this is potentially a generic Rails issue?

**Comment by kaspth** [comment]
That bundling and yarning is needed doesn't seem that farfetched, that's what Rails' bin/setup convention is about capturing for instance.

The assets compile has been an issue on CI too, I can't figure how to get `yarn build:css` to use a cache.

@KonnorRogers have you encountered something like this with the assets stuff you've looked into?

**Comment by KonnorRogers** [comment]
@kaspth this is expected behavior. You could check if "public/assets/.sprockets-manifest- {UUID}.json" exists in the test environment before loading the environment in "test/test_helper"

although it doesn't guard against stale assets. But yea there's ways to fix this. Just a matter of which you value, always having fresh assets or just doing a check that a manifest exists.

**Comment by KonnorRogers** [comment]
https://github.com/rails/jsbundling-rails/blob/b10503105a4ceb26358a39fffa0c5fd351bac3f7/lib/tasks/jsbundling/build.rake#L14-L20

^ these are the tasks you can also define to run a build everytime.

**Comment by kaspth** [comment]
Here's a fresh clone without having done `bundle install; yarn install; bin/dev` and it looks like it's already running `javascript:build` automatically:

```
3.2.1 ~/code/bullet-train-co/starter main = bin/rails test:system
^Crails aborted!
Interrupt: 

Tasks: TOP => test:system => test:prepare => javascript:build
```

**Comment by kaspth** [comment]
hm, in the clone ^ with node v19.7.0 `yarn install` doesn't print anything in my terminal and seemingly just takes forever. Cool.

**Comment by kaspth** [comment]
Ok, I just made another clone. If I run `nodenv local 19.3.0` first, then `bin/rails test:system` works flawlessly. It runs `yarn install` and compiles assets — and the system tests just run and pass (there's two unrelated OpenAPI ones that fail).

@andrewculver if you run what a new clone what does `node -v` say? If I used `19.7.0` things didn't work at all — I'm not sure what's going on with that, but that's outta my wheelhouse.

**Comment by kaspth** [comment]
@KonnorRogers thank you for chiming in here! It helped me figure out how to investigate this a little more.

**Comment by kaspth** [comment]
@KonnorRogers thank you for chiming in here! It helped me figure out how to investigate this a little more.

**Comment by jagthedrummer** [comment]
I just did a fresh clone, ran `bin/configure` and `bin/setup` and then ran the system tests and it built the assets before running the tests and the tests passed. I think this was fixed somewhere along the way.
