### ISSUE TITLE
Conditionally run github merge action

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#703]
https://github.com/bullet-train-co/bullet_train/blob/a17e073d4a09786b2c7b188e7cc83d4c3816a455/.github/workflows/main.yml#L3-L6

This action seems to be convenient for the maintainers, but may not be at all useful for downstream projects.  Perhaps it needs to be configured to run conditionally when the repo matches `bullet-train-co/bullet_train`.

https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

I'm not sure if downstream projects would want to use it, but maybe they could make a copy without the condition in a different workflow file to avoid merge conflicts.

Related to #699

**Comment by jagthedrummer** [comment]
We removed the file in question recently.
