### ISSUE TITLE
@bullet-train/fields npm package needs update

### ISSUE THREAD

**Issue by itodca** [bullet-train-co/bullet_train#731]
It looks like the the `@bullet-train/fields` npm package needs to be updated to include the latest code in the BulletTrain::Fields repo. The Rails view code is referencing methods that do not exist in the corresponding stimulus controller for the super-select component.

Found when noticing a console error while focusing on a super-select field:
![image](https://user-images.githubusercontent.com/2732506/232406970-375651de-a4ff-4973-bc4b-709809ebc01f.png)

**Comment by jagthedrummer** [comment]
Thanks for the report, @itodca. And sorry it went with no response for so long. We recently automated the process of publishing gems and packages simultaneously, so things should stay in better sync moving forward.
