### ISSUE TITLE
package.json broken, css build not working

### ISSUE THREAD

**Issue by abuisman** [bullet-train-co/bullet_train#744]
When trying to get Bullet train up and running I ran into an issue where CSS compiling didn't work.

The cause is in the package.json:

```json
"scripts": {
    "build": "THEME=\"light\" node esbuild.config.js",
    "build:css": "bin/link; THEME=\"light\" yarn build; yarn light:build:css; yarn light:build:mailer:css",
    "light:build:css": "THEME=\"light\" NODE_PATH=./node_modules tailwindcss -c tailwind.config.js -i `bundle exec bin/theme tailwind-stylesheet light` -o ./app/assets/builds/application.light.css --postcss ./postcss.config.js",
    "light:build:mailer:css": "NODE_PATH=./node_modules tailwindcss -c `bundle exec bin/theme tailwind-mailer-config light` -i `bundle exec bin/theme tailwind-stylesheet light` -o ./app/assets/builds/application.mailer.light.css --postcss ./postcss.mailer.config.js"
  }
```

The syntax ```bundle`` doesn't work and it has to be `$(bundle ...)` instead. So:

```json
  "scripts": {
    "build": "THEME=light node esbuild.config.js",
    "build:css": "bin/link; THEME=light yarn build; yarn light:build:css; yarn light:build:mailer:css",
    "light:build:css": "THEME=light NODE_PATH=./node_modules tailwindcss -c tailwind.config.js -i $(bundle exec bin/theme tailwind-stylesheet light) -o ./app/assets/builds/application.light.css --postcss ./postcss.config.js",
    "light:build:mailer:css": "NODE_PATH=./node_modules tailwindcss -c $(bundle exec bin/theme tailwind-mailer-config light) -i $(bundle exec bin/theme tailwind-stylesheet light) -o ./app/assets/builds/application.mailer.light.css --postcss ./postcss.mailer.config.js"
  }
```

Also I removed the quotes around "light" which helped with a file `application."light".js` being created.

I don't know if this is a very portable version of the file, so I didn't create a PR.

I am on yarn version: `3.5.0`

**Comment by olbrich** [comment]
@abuisman what shell/OS are you using? These scripts seem to work fine on MacOS with zsh.

**Comment by gazayas** [comment]
I'm not getting the same error that was on Discord, but I'm definitely getting a bunch of issues when upgrading to yarn 3.5.0. I have to run every process individually for it to work, plus I had to run `yarn add @hotwired/turbo-rails` as well as add a `@` to `stimulus/webpack-helpers` [here](https://github.com/bullet-train-co/bullet_train/blob/53235ee4f43f080938afe167869b4996554965e1/app/javascript/controllers/index.js#L2).

Still can't run `bin/dev`, getting a lot of bootsnap errors.

**Comment by gazayas** [comment]
Confirmed that the `$(bundle ...)` syntax works with Mac without having to make the changes mentioned in the previous comment. The platform I was originally having issues with was Linux so I'll have to double check there.
