### ISSUE TITLE
Uncaught ReferenceError: jstz is not defined

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#747]
After signing up the time zone select box stays on the first option in the list `(GMT-12:00) International Date Line West` and the developer console shows an error.

```
Uncaught ReferenceError: jstz is not defined
    <anonymous> edit line 30891 > injectedScript:160
    jQuery 2
    dispatch turbo.es2017-esm.js:315
    notifyApplicationAfterPageLoad turbo.es2017-esm.js:2729
    visitCompleted turbo.es2017-esm.js:2647
    visitCompleted turbo.es2017-esm.js:2126
    complete turbo.es2017-esm.js:1454
    loadResponse turbo.es2017-esm.js:1519
edit line 30891 > injectedScript:160:22
    <anonymous> edit line 30891 > injectedScript:160
    jQuery 2
    dispatch turbo.es2017-esm.js:315
    notifyApplicationAfterPageLoad turbo.es2017-esm.js:2729
    visitCompleted turbo.es2017-esm.js:2647
    visitCompleted turbo.es2017-esm.js:2126
    complete turbo.es2017-esm.js:1454
    loadResponse turbo.es2017-esm.js:1519
    InterpretGeneratorResume self-hosted:1413
    AsyncFunctionNext self-hosted:810

```

**Comment by gazayas** [comment]
Hey @jagthedrummer, this seems vaguely familiar but I'm having trouble reproducing the problem. Would you mind giving more specific steps?

By the way, I AM getting <i>this</i> error which is probably worth noting as well:
![Screenshot from 2023-05-10 18-49-40](https://github.com/bullet-train-co/bullet_train/assets/10546292/3216b326-32f2-4b2b-b8bc-3a2bab1da954)

**Comment by gazayas** [comment]
Turns out the Stimulus controller error is unrelated, but I found the cause so I'll link the issue here: https://github.com/bullet-train-co/bullet_train-core/issues/290

**Comment by jagthedrummer** [comment]
Seems like this was related to npm packages being out of date with the gems. New versions are out since this was opened, and we now have an automated release process that releases gems and npm packages at the same time.
