### ISSUE TITLE
Testing workflow for GitHub

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#764]
It would be nice to have a working GitHub workflow included with the starter repo.

Circle is OK, but since all of the docs are built around an assumption of using GitHub it would be super convenient to have a testing pipeline working out of the box with not additional configuration or services required.

**Comment by gazayas** [comment]
Linking https://github.com/bullet-train-co/bullet_train/pull/186 here

Not sure about the progress there, but it's definitely been considered.
