### ISSUE TITLE
Pagination test is flaky

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#765]
For some reason the [pagination system test](https://github.com/bullet-train-co/bullet_train/blob/main/test/system/pagination_test.rb) is failing for me in CI, but not locally.

[This line is failing for me](https://github.com/bullet-train-co/bullet_train/blob/main/test/system/pagination_test.rb#L25):

```ruby
refute page.has_content?("Test #{Pagy::DEFAULT[:items] + 1}")
```

The page size is 20, so that line is looking for the string "Test 21" in the page content, and is finding it even though it should not be found.

After much head scratching and debugging I _finally_ figured out that for some reason the sort order in CI is backwards. (I have no idea why that might be the case.)

So "Test 21" is actually on the page, but the first item "Test 1" is missing.

**But** there's actually a test to check for "Test 1" that is passing when it shouldn't pass. And that's because we're doing simple substring matching and "Test 1" also matches "Test 11", "Test 12", etc...

**Comment by gazayas** [comment]
> But there's actually a test to check for "Test 1" that is passing when it shouldn't pass. And that's because we're doing simple substring matching and "Test 1" also matches "Test 11", "Test 12", etc...

Good point, I think this would be a better check:
```ruby
page.text.scan(/Test \d+/).include?("Test 1")
```

> After much head scratching and debugging I finally figured out that for some reason the sort order in CI is backwards. (I have no idea why that might be the case.)

I wonder why it's getting displayed backwards? I'm not sure if this is something on Bullet Train's side.

**Comment by jagthedrummer** [comment]
Probably related to https://github.com/bullet-train-co/bullet_train-core/issues/408
