### ISSUE TITLE
Command `yarn check` displays an error with Yarn 2 and above

### ISSUE THREAD

**Issue by goulvench** [bullet-train-co/bullet_train#781]
When running `bin/setup` using Yarn 2 or greater, the [`yarn check`](https://github.com/bullet-train-co/bullet_train/blob/main/bin/setup#L35) command displays the following error:
```bash
Usage Error: Couldn't find a script named "check".
```

`yarn check` has been [removed in Yarn v2](https://github.com/yarnpkg/rfcs/pull/106).

The [migration guide](https://yarnpkg.com/getting-started/migration#removed-from-core) indicates that `yarn install` perform the required checks, so apart from a warning, this has no side-effects.

One solution to get rid of this warning would be to check Yarn version before running this command:
```ruby
if command?("yarn") && `yarn -v`.to_f < 2
  system("yarn check") || system!("yarn install")
else
  system!("yarn install")
end
```

Should I wrap this change in a Pull Request?

**Comment by gazayas** [comment]
@goulvench Yes, that would be great! I confirmed that this works for older and more recent versions of yarn, so feel free to submit a PR at any time.

**Comment by gazayas** [comment]
Also waiting for some newer package versions to be merged in after installing with yarn 3:
- https://github.com/bullet-train-co/bullet_train/pull/754

We'll have to keep an eye out if there are any other things we have to change when upgrading.
