### ISSUE TITLE
First time bin/setup failures

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#788]
When running `bin/setup` immediately after installing a new ruby version (or probably starting with the project), the setup script will fail because it requires 'colorize', which probably is not installed

https://github.com/bullet-train-co/bullet_train/blob/616b9552193ddecdb4fa59fb8360fc4aaddcf9ef/bin/setup#L1-L3

This forces the user to install `colorize` manually, which is just annoying.

This can be remedied by using [bundler/inline](https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html)

**Comment by jagthedrummer** [comment]
This was fixed in #789.
