### ISSUE TITLE
Proposal to introduce API only mode

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#790]
We can do the following to create an api-only application in rails:
```
> rails new application_name --api
```

Since we have a lot of powerful API logic in Bullet Train, I thought it would make sense for developers to run one of the following two commands to setup their application for API mode.

## 1. `bin/configure --api`
After cloning the repository, developers would run `bin/configure --api` to remove any unnecessary files so they only have what they need for an backend API. This feels semi-unintuitive because rails creates an api-only application on `rails new`. However, I think using our equivalent to `rails new` presents some of its own issues, which I'll mention here next.

## 2. `git clone`

```
> git clone --branch api-only git@github.com:bullet-train-co/bullet_train.git application_name
```

Here we would maintain an `api-only` branch which would look similar to `main`, except that it would only have the files necessary for an api-only application. The problem is that I feel like it would be pretty hard to maintain one apart from `main`, and it would also be pretty tough to just make an altogether new, different `bullet_train` API starter repository just for this purpose. Yes, it's similar to `rails new` which would make sense for most developers upfront, but if all we have to do is add `--api` for `bin/configure`, then that's probably a better option when considering all of the files we have to maintain.

## Afterthoughts
If we <i>were</i> to implement this, I think `bin/configure --api` would be all-around easier to maintain. However, if we already have a way to implement an api-only application that I'm just missing, I'd be glad to re-think through things.

**Comment by newstler** [comment]
I vote for `bin/configure --api` as well. It seems there should be a file containing the list of all those unneeded files in API only mode, — that way it would be easier to maintain both versions, and code for `--api` configuration would be written only once.

**Comment by olbrich** [comment]
Do you think it's likely that someone may start with an API-only app and decide to add the conventional web UI at a later date? If so, what would that look like?

On a related note, there's probably also a use case for `--no-api` that would skip adding API support.

**Comment by newstler** [comment]
If that scenario is possible, then probably it would require to break all app to modules of UI, API and some core functionality required by both. Then, depending on '--api-only'/'--no-api' options appropriate modules should be used during configuration.

**Comment by jagthedrummer** [comment]
This seems like a very big lift to me, and I'm not sure if it would be used that often. In my mind all of the UI stuff that BT provides is the main draw. Have people asked for this?

**Comment by gazayas** [comment]
> Have people asked for this?

Not particularly, and last time I talked to Andrew about this it didn't seem to him like it was something we need push forward.

**Comment by jagthedrummer** [comment]
OK, then I propose that we close this and the WIP PR, just so that we have less stuff to wade through. I'll leave that up to you though @gazayas.
