### ISSUE TITLE
Super Select with remote search

### ISSUE THREAD

**Issue by tangopium** [bullet-train-co/bullet_train#804]
Is it possible to implement a remote search with super select? I have thousands of entries in my database and loading all of them into the browser wouldn't work. Select2 itself supports this option (https://select2.org/data-sources/ajax). Can someone guide me to a bullettrain-compatible solution?

**Comment by gazayas** [comment]
@tangopium We currently have select2 options embedded within the `bullet_train-fields` gem, and you can see where we call the `ajax` option here:
https://github.com/bullet-train-co/bullet_train-core/blob/350023aa4c3116f4df89c85f6dd2d7dbf8261bbf/bullet_train-fields/app/javascript/controllers/fields/super_select_controller.js#L56-L70

We discussed exposing the options [here](https://github.com/bullet-train-co/bullet_train-core/pull/310#issuecomment-1567370901) so developers could write their own custom options inside their Bullet Train app without having to eject or edit any files within any of the `bullet_train` gems working under the hood. In this comment, you can see specifically what should be done to use the `ajax: {...}` option. The pull request is still open, but we definitely want to expose these options soon.

With that being said, I'm seeing we have a `searchUrlValue` attribute in our Stimulus controller which is passed to the ajax url, I'm just not seeing a definition for it anywhere. Any thoughts on this one @pascallaliberte?

**Comment by pascallaliberte** [comment]
@gazayas the `searchUrlValue` is set by defining the `choices_url` local on the partial:

https://github.com/bullet-train-co/bullet_train-core/blob/350023aa4c3116f4df89c85f6dd2d7dbf8261bbf/bullet_train-themes/app/views/themes/base/fields/_super_select.html.erb#L28

I think that should do it. However, the `choices_url` provided should be an endpoint that returns data in `select2` default format. (I believe it's a simple array of objects with `id` and `text` attributes?)

To allow for another JSON output and by specifying a custom `. processResults` callback from `select2` , currently, our recommendation is to eject and override both the `super_select.html.erb` and `super_select_controller.js` files, rename them to some other name locally for that kind of field.

**Comment by jagthedrummer** [comment]
I think this should have been added in https://github.com/bullet-train-co/bullet_train-core/pull/310

**Comment by pascallaliberte** [comment]
@tangopium have you found a solution that works for you, either through using `choices_url` or by ejecting and duplicating into a renamed `super_select` field with a custom `processResults` callback?

Was your endpoint a scaffolded json API from BT?

**Comment by jagthedrummer** [comment]
@pascallaliberte, did I misunderstand about this being added? Should we reopen this?
