### ISSUE TITLE
enable_cable_ready_updates

### ISSUE THREAD

**Issue by Meekohi** [bullet-train-co/bullet_train#805]
I get several warnings like this on a new install, when running `bin/setup`:
```
DEPRECATED: please use `enable_cable_ready_updates` instead. The `enable_updates` class method will be removed from a future version of CableReady 5
```

**Comment by gazayas** [comment]
- https://github.com/bullet-train-co/bullet_train-core/issues/127
- https://github.com/bullet-train-co/bullet_train-core/pull/305
