### ISSUE TITLE
Use specific version of capybara instead of the main branch of the codebase

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train#808]
https://github.com/bullet-train-co/bullet_train/blob/56914548b0a2718300eaa3a733eb9b168afb9214/Gemfile#L85

I'm not sure why this was introduced, so research may be required. If possible this should specify a minimum gem version number instead of using whatever is the latest commit on the main branch. If the main branch is required, a comment explaining why it's required should be added.

**Comment by gazayas** [comment]
- https://github.com/bullet-train-co/bullet_train/pull/75

There were some deprecations that were showing up related to [this issue in capybara](https://github.com/teamcapybara/capybara/issues/2511), and at the time the latest branch hadn't been released so we used the GitHub branch. We can most likely use the latest stable release now, so I'll try to look into that soon.
