### ISSUE TITLE
bin/configure fails after setting remote

### ISSUE THREAD

**Issue by alterisian** [bullet-train-co/bullet_train#9]
bin/configure
Bullet Train requires Ruby 3.0.0 and `ruby -v` returns ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux].
Bullet Train requires Node.js 16.14.0 and `node -v` returns v16.14.0.
Renaming repository `origin` remote to `bullet-train`.
Hit <Return> and we'll open a browser to GitHub where you can create a new repository. When you're done, copy the SSH path from the new repository and return here. We'll ask you to paste it to us in the next step.

bin/configure:89:in ``': No such file or directory - open (Errno::ENOENT)
	from bin/configure:89:in `<main>'
oceanician@River:~/projects/rails7_jobboard/bullet$ bin/configure
Bullet Train requires Ruby 3.0.0 and `ruby -v` returns ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux].
Bullet Train requires Node.js 16.14.0 and `node -v` returns v16.14.0.
Repository already has a `bullet-train` remote.
Hit <Return> and we'll open a browser to GitHub where you can create a new repository. When you're done, copy the SSH path from the new repository and return here. We'll ask you to paste it to us in the next step.

bin/configure:89:in ``': No such file or directory - open (Errno::ENOENT)
	from bin/configure:89:in `<main>'
	
	
(Linux. )

**Comment by andrewculver** [comment]
@gazayas Merged! Sorry to have missed that before the announcement!

@alterisian If you start from scratch now, it should be fixed! Sorry for the trouble!
