### ISSUE TITLE
Agument list too long error during bin/setup

### ISSUE THREAD

**Issue by seanders** [bullet-train-co/bullet_train#902]
I'm running `bin/setup` for the very first time and it's been running for maybe ~10 minutes now. Not sure what's going on here.

<img width="900" alt="image" src="https://github.com/bullet-train-co/bullet_train/assets/2849183/f952f0df-5917-4b73-bacf-672e1a6414ab">

<details>
  <summary>Full Output (click me)</summary>
  
== Checking dependencies ==
Overmind not found
We recommend installing overmind to run your application processes
Visit https://github.com/DarthSim/overmind#installation for more information.
== Installing dependencies ==
The Gemfile's dependencies are satisfied
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/Users/sean/.rbenv/plugins/rbenv-vars/etc/rbenv.d/exec/rbenv-vars.bash: line 3: /Users/sean/.rbenv/plugins/rbenv-vars/bin/rbenv-vars: Argument list too long
/usr/local/Cellar/rbenv/1.2.0/libexec/rbenv-exec: line 47: /Users/sean/workspace/evidence_snap_backend/bin/yarn: Argument list too long
</details>

**Updates**

* This seems related to the rbenv shim for yarn. I'm on ruby 3.2.2 (the versions bulletrain requires), and it seems to be using the `.rbenv/shim/yarn` but that gem isn't actually installed. I _think_ thats why yarn is just failing out.

**Comment by jagthedrummer** [comment]
@seanders I haven't seen that before, but it looks like it might have to do with your `rbenv` setup. What do the files mentioned in the error look like?

**Comment by seanders** [comment]
@jagthedrummer Looks like this was mainly an issue caused by rbenv-binstubs.

I generated new binstubs in `./bundle/bin`, then did `rbenv rehash` and that seemed to fix the problem.

(I thikn the rehash was the actual solution?)

**Comment by jagthedrummer** [comment]
🤘 Glad you got it figured out!

**Comment by jagthedrummer** [comment]
@seanders There's a PR that's been open for a while about adding Docker support, but we're not entirely sure if we want to take on the burden of maintaining that setup.

https://github.com/bullet-train-co/bullet_train/pull/464

I'll chat with some of the other core team members and see if we can come to a decision.

If you have any improvements to suggest on that PR we'd love to hear 'em. Or if you'd take a very different approach, we'd like to know about that too.
