### ISSUE TITLE
Fix open api test

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#912]
In #749 we introduced more stringent checks in validating the Open API doc. https://github.com/bullet-train-co/bullet_train/pull/749/files#diff-c04c1d7b8b2c28801ca5fc5cfa976e08c1f9731284f8ad655655b2a12d9bcef6

After merging that, I also merged https://github.com/bullet-train-co/bullet_train-core/pull/257 and https://github.com/bullet-train-co/bullet_train/pull/737 which were both passing prior to merging.

I think that they probably would have failed that new test if their branches had been up to date. Since failing the tests if the doc is invalid is a brand new introduction, I'm going to disable those assertions in that test. And will link to this issue in a `TODO`.

Here's the PR where I disabled the parts of the test that were failing: https://github.com/bullet-train-co/bullet_train/pull/913

**Comment by jagthedrummer** [comment]
@newstler, just so you're aware, it looks like the Invitations API stuff wasn't up to snuff with the more stringent Open API checks that you added in #749. I don't know enough about the Open API stuff to be able to whip up a quick fix, so I'm disabling the failing parts of that test for now.

**Comment by newstler** [comment]
@jagthedrummer Fixed the bug and switched the test back in those two joint PRs:

https://github.com/bullet-train-co/bullet_train-core/pull/472
https://github.com/bullet-train-co/bullet_train/pull/915

**Comment by olbrich** [comment]
I haven't tried it before, but think you can use [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux).  Combine that with a Brewfile, and you might be able to generalize the installation of non-gem dependencies.
