### ISSUE TITLE
Duplicate test?

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#922]
I think that this test https://github.com/bullet-train-co/bullet_train/blob/main/test/system/super_scaffolding_test.rb#L286-L290 has been superseded by this more in-depth test https://github.com/bullet-train-co/bullet_train/blob/main/test/controllers/api/open_api_controller_test.rb#L4-L19. Which I think means we could remove the old one.

@newstler, does that sound right to you?

**Comment by jagthedrummer** [comment]
Actually, after looking at it some more I think that the test _is_ redundant, but that we want to keep it. Or at least some version of it. It's part of `super_scaffolding_test.rb` which is kind of a special test that we run in CI after generating a bunch of new models and super scaffolds. So I think this particular instance of the test is meant to ensure that the OpenAPI doc continues to be valid after we generate new models and scaffolds.

Or maybe we don't need the separate controller test version?

**Comment by jagthedrummer** [comment]
Or maybe we should explicitly run the separate controller test after running the other super scaffolding tests...

**Comment by jagthedrummer** [comment]
I also think that this test https://github.com/bullet-train-co/bullet_train/blob/main/test/system/super_scaffolding_test.rb#L286-L290 is causing test failures when people run the tests locally.

For example:
https://discord.com/channels/836637622432170028/836637623048601633/1144621336866586755

I ran into it when working on this PR https://github.com/bullet-train-co/bullet_train/pull/921. I think the change I have in that PR should resolve the problem, but probably doesn't need to be entangled with the cuprite stuff.

I _think_ the issue is that the test is sidestepping capybara and calling an endpoint directly that ends up creating database records which are not cleaned up in the normal post-test process. Not entirely sure. Will look at it firs thing next week.

**Comment by gazayas** [comment]
> It's part of super_scaffolding_test.rb which is kind of a special test that we run in CI after generating a bunch of new models and super scaffolds. So I think this particular instance of the test is meant to ensure that the OpenAPI doc continues to be valid after we generate new models and scaffolds.

@jagthedrummer Yes, the Super Scaffolding system tests are usually run in isolation, so I'm for keeping the test even though we technically do the same thing somewhere else.

All of our system tests <i>should</i> pass after running the Super Scaffolding test setup script, but we don't do that in CI, and it's not guaranteed that developers using Bullet Train will do so either.

**Comment by jagthedrummer** [comment]
Closing this because we need the redundancy to ensure that super scaffolding processes don't break the OpenAPI document.
