### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#926]
We have some sort of order-dependent flakiness in the test suite. I can reliably get a failure locally by doing:

```
rails db:test:prepare; rails test --seed 46583
```

```
🌱 Generating global seeds.
🌱 Generating test environment seeds.
Coverage report generated for Minitest to /Users/jgreen/projects/bullet-train-co/bullet_train/coverage. 0 / 226 LOC (0.0%) covered.
Started with run options --seed 46583

InvitationTest
  test_must_be_valid                                              PASS (0.68s)
  test_must_set_uuid                                              PASS (0.37s)
  test_accept_for_must_destroy_invitation                         PASS (0.42s)
  test_accept_for_must_set_team                                   PASS (0.37s)

Api::V1::UsersControllerTest
  test_index                                                      PASS (0.90s)
  test_show                                                       PASS (0.73s)

BaseTest
  test_`seeding?`_returns_true_when_running_db:seed               PASS (1.68s)

Api::OpenApiControllerTest
  test_OpenAPI_document_is_valid                                 ERROR (1.17s)
Minitest::UnexpectedError:         RuntimeError: Neutered Exception ActionView::Template::Error: PG::ForeignKeyViolation: ERROR:  insert or update on table "memberships" violates foreign key constraint "fk_rails_688bbf8b6a"
        DETAIL:  Key (added_by_id)=(27) is not present in table "memberships".

            app/views/api/v1/open_api/index.yaml.erb:20
            test/controllers/api/open_api_controller_test.rb:9:in `block in <class:OpenApiControllerTest>'
```

**Comment by olbrich** [comment]
@jagthedrummer I think this is the FK problem that I found in bullet-train-co/bullet_train-core#482

**Comment by jagthedrummer** [comment]
@olbrich I thought it was that at first, but it's still happening when I'm testing against your branch (and now `main`).

**Comment by jagthedrummer** [comment]
I've found a few ways to make the error go away, but I'm not entirely sure that any of them put us on the right path for finding a real answer.

1. Add a `skip` to the top of the `setup` method in `test/controllers/api/v1/users_controller_test.rb` (https://github.com/bullet-train-co/bullet_train/blob/main/test/controllers/api/v1/users_controller_test.rb#L4)
2. Comment out (or remove) the unused `@users = create_list(:user, 3)` variable in that same `setup` method. (https://github.com/bullet-train-co/bullet_train/blob/main/test/controllers/api/v1/users_controller_test.rb#L8C5-L8C35)
3. Comment out (or remove) the `added_by_id { FactoryBot.example(:user).id }` line in the factory for memberships `test/factories/memberships.rb`. (https://github.com/bullet-train-co/bullet_train/blob/main/test/factories/memberships.rb#L14)

**Comment by jagthedrummer** [comment]
I think I'm getting closer. I realized that this line in the Memberships factory is invalid:

```
added_by_id { FactoryBot.example(:user).id }
```

`added_by_id` is indexed to the `membership` table, not to `users`. So, what's happening is that we're creating (and then deleting) a `User` by calling `FactoryBot.example(:user)` and then we're shoving the id of that (now deleted) `User` into a column that's indexed on the `memberships` table. If we just so happen to have a record in the `memberships` table that has that ID then we can get past this problematic point. If not, everything blows up.

I tried fixing that line to generate a `membership` instead, and that causes a different error.

```
Minitest::UnexpectedError:         SystemStackError: stack level too deep
```

That's because we have an infinite loop of creating a membership that was the `added_by` of the membership we're creating, which needs a membership for `added_by`, which needs a membership for `added_by`.

Maybe we just remove that line completely?

(Relatedly, I feel _very_ uneasy about the way that `ExampleBot` generates records. I don't know much about it, or how it got to be the way that it is, so I could be way off base. But it doesn't generally seem like a good idea to do things that require us to be resetting PK sequences. And the pattern of creating a record, cloning it, then rolling back that record, then returning the cloned object that has an ID that no longer exists in the database strikes me as _super_ weird.)

**Comment by gazayas** [comment]
@jagthedrummer Good find, I didn't realize that we were trying to grab a User ID for `added_by` in that factory.

I'm personally for setting `added_by` to `nil` by default in the factory (or not having it at all), and making a note saying this is usually populated when creating invitations.

For example, we have this in the [invitation details test](https://github.com/bullet-train-co/bullet_train/blob/main/test/system/invitation_details_test.rb#L52-L53):

```ruby
membership = Membership.new(team: @jane.current_team, user_email: @john.email)
binding.pry
create :invitation, team: @jane.current_team, from_membership: @jane.memberships.first, email: @john.email, membership: membership
```

At the breakpoint `membership.added_by` is `nil` but gets populated after creating the Invitation, so although we're not explicitly declaring `added_by_id` in the tests, it's still working because `added_by` is populated automatically.

If not declaring `added_by` explicitly in the tests would cause confusion, then I think adding a note in the factory (where developers would most likely go to figure out how to define their FactoryBot examples) would help prevent any confusion, and developers would know to look for the attribute after creating an invitation. What do you think?

**Comment by jagthedrummer** [comment]
@gazayas, thanks for the context on this!

Generally I don't have strong feelings about whether an attribute should be declared but set to `nil` in a factory vs just being left out completely. But in this particular case, I think you make a good point about leaving some sort of note about it in the factory, just because it does have the potential to cause trouble.

So, maybe we should set it to `nil` and mention the potential for an infinite loop if you try to auto-populate with a FactoryBot membership.
