### ISSUE TITLE
Do we really need Overmind?

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#953]
We complain if the `overmind` command isn't found, but do we really need it?

https://github.com/bullet-train-co/bullet_train/blob/bbf3578c567908e28150e81498fe4943b8351b2f/bin/setup#L29C1-L36

(Just trying to help someone through the firs setup and making notes of rough spots.)

**Comment by gazayas** [comment]
Pinning the original conversation here for context:

https://discord.com/channels/836637622432170028/836637623048601633/966326175335063602

**Comment by jagthedrummer** [comment]
Thanks, @gazayas! I didn't realize that `overmind` did that kind of stuff. Maybe we should add some developer docs about why we use it by default and what you can do with it.

I was just surprised yesterday when I realized that `overmind` is part of `tmux` and thought "why do we need people to have tmux?"

**Comment by jagthedrummer** [comment]
My question was answered, so this issue can be closed.
