### ISSUE TITLE
Run `rails g model` in `bin/super-scaffold` step

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#988]
Mentioned [here](https://github.com/bullet-train-co/bullet_train-core/pull/515#issuecomment-1708647196) in https://github.com/bullet-train-co/bullet_train-core/pull/515.

Since we presuppose data types for model attributes when Super Scaffolding a model, it would be easier to run migrations as a part of `bin/super-scaffold crud`, etc.

So, instead of running the following...

```
rails g model Project team:references title:string
bin/super-scaffold crud Project Team title:text_field
```

We could just run this:
```
bin/super-scaffold crud Project Team title:text_field
```

As far as I know, I don't think there are any field partials that use differing data types besides cloudinary images and ActiveRecord images (see https://github.com/bullet-train-co/bullet_train-core/pull/515 for more details).

However, there are multiple types of scaffolders (`crud-field`, `incoming-webhooks`, etc.), so we would have to consider if this would be counter-productive to these scaffolders.

Are there any steps between `rails g model` and `bin/super-scaffold crud` that would want use to separate the two exclusively? We could at least start a PR for `bin/super-scaffold crud` and see where it takes us.

cc/ @andrewculver @jagthedrummer

**Comment by jagthedrummer** [comment]
I love the idea of this. I think we could alter `crud-field` in a similar way. So instead of having to generate a migration and then the field, you just generate the `crud-field` and we generate the migration for you.

**Comment by gazayas** [comment]
Working on an app of my own, I’m finding that I want to separate the steps to add attributes in my model that won’t show up on the Super Scaffolded form. However, I don’t think that means we should completely trash this idea. We could pass a flag like `—skip-model-generation` or `--skip-migration` (we already have a [--skip-model](https://bullettrain.co/docs/super-scaffolding/options) option).

Another use-case for this is [join models](https://bullettrain.co/docs/super-scaffolding#6-scaffolding-has-many-through-associations-with-join-model). Here is an example from the documentation:
```
rails g model Projects::Tag team:references name:string
bin/super-scaffold crud Projects::Tag Team name:text_field

rails g model Projects::AppliedTag project:references tag:references
bin/super-scaffold join-model Projects::AppliedTag project_id{class_name=Project} tag_id{class_name=Projects::Tag}

bin/super-scaffold crud-field Project tag_ids:super_select{class_name=Projects::Tag}
rake db:migrate
```

By the time we get to the last Super Scaffolding command, we already have all that we need model-wise, so we don’t need to run another migration here (like we usually do when just adding a normal `crud-field`).

So, I think as long as we have a flag to be able to skip (or enable? `-—generate-model`?) this functionality, we’ll be fine.
