### ISSUE TITLE
Bundle install not working fine in main branch

### ISSUE THREAD

**Issue by hassanharoon86** [bullet-train-co/bullet_train#996]
Running `bin/configure`, `bin/setup` or even `bundle install` after cloning the project giving this error:

An error occurred while installing charlock_holmes (0.7.7), and Bundler cannot continue.

In Gemfile:
  bullet_train-api was resolved to 1.4.1, which depends on
    bullet_train was resolved to 1.4.1, which depends on
      extended_email_reply_parser was resolved to 0.5.1, which depends on
        charlock_holmes

![image](https://github.com/bullet-train-co/bullet_train/assets/72931289/8ce8d080-1759-4ba6-826c-2519ce552fd3)

**Comment by gazayas** [comment]
Possibly related to #854

**Comment by hassanharoon86** [comment]
> Possibly related to #854

Yes, doing `bundle pristine charlock_holmes` resolved it.

**Comment by gazayas** [comment]
@hassanharoon86 Awesome, thanks for confirming.
